// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v6.32.1
// source: api/layerstore/v1/layerstore.proto

package layerstorepb

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	LayerStore_PullImage_FullMethodName = "/layerstore.v1.LayerStore/PullImage"
	LayerStore_StatLayer_FullMethodName = "/layerstore.v1.LayerStore/StatLayer"
	LayerStore_ReadLayer_FullMethodName = "/layerstore.v1.LayerStore/ReadLayer"
	LayerStore_HasLayer_FullMethodName  = "/layerstore.v1.LayerStore/HasLayer"
	LayerStore_HasImage_FullMethodName  = "/layerstore.v1.LayerStore/HasImage"
)

// LayerStoreClient is the client API for LayerStore service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type LayerStoreClient interface {
	PullImage(ctx context.Context, in *PullImageRequest, opts ...grpc.CallOption) (*PullImageResponse, error)
	StatLayer(ctx context.Context, in *StatLayerRequest, opts ...grpc.CallOption) (*StatLayerResponse, error)
	ReadLayer(ctx context.Context, in *ReadLayerRequest, opts ...grpc.CallOption) (*ReadLayerResponse, error)
	HasLayer(ctx context.Context, in *HasLayerRequest, opts ...grpc.CallOption) (*HasLayerResponse, error)
	HasImage(ctx context.Context, in *HasImageRequest, opts ...grpc.CallOption) (*HasImageResponse, error)
}

type layerStoreClient struct {
	cc grpc.ClientConnInterface
}

func NewLayerStoreClient(cc grpc.ClientConnInterface) LayerStoreClient {
	return &layerStoreClient{cc}
}

func (c *layerStoreClient) PullImage(ctx context.Context, in *PullImageRequest, opts ...grpc.CallOption) (*PullImageResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(PullImageResponse)
	err := c.cc.Invoke(ctx, LayerStore_PullImage_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *layerStoreClient) StatLayer(ctx context.Context, in *StatLayerRequest, opts ...grpc.CallOption) (*StatLayerResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(StatLayerResponse)
	err := c.cc.Invoke(ctx, LayerStore_StatLayer_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *layerStoreClient) ReadLayer(ctx context.Context, in *ReadLayerRequest, opts ...grpc.CallOption) (*ReadLayerResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ReadLayerResponse)
	err := c.cc.Invoke(ctx, LayerStore_ReadLayer_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *layerStoreClient) HasLayer(ctx context.Context, in *HasLayerRequest, opts ...grpc.CallOption) (*HasLayerResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(HasLayerResponse)
	err := c.cc.Invoke(ctx, LayerStore_HasLayer_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *layerStoreClient) HasImage(ctx context.Context, in *HasImageRequest, opts ...grpc.CallOption) (*HasImageResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(HasImageResponse)
	err := c.cc.Invoke(ctx, LayerStore_HasImage_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// LayerStoreServer is the server API for LayerStore service.
// All implementations must embed UnimplementedLayerStoreServer
// for forward compatibility.
type LayerStoreServer interface {
	PullImage(context.Context, *PullImageRequest) (*PullImageResponse, error)
	StatLayer(context.Context, *StatLayerRequest) (*StatLayerResponse, error)
	ReadLayer(context.Context, *ReadLayerRequest) (*ReadLayerResponse, error)
	HasLayer(context.Context, *HasLayerRequest) (*HasLayerResponse, error)
	HasImage(context.Context, *HasImageRequest) (*HasImageResponse, error)
	mustEmbedUnimplementedLayerStoreServer()
}

// UnimplementedLayerStoreServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedLayerStoreServer struct{}

func (UnimplementedLayerStoreServer) PullImage(context.Context, *PullImageRequest) (*PullImageResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method PullImage not implemented")
}
func (UnimplementedLayerStoreServer) StatLayer(context.Context, *StatLayerRequest) (*StatLayerResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method StatLayer not implemented")
}
func (UnimplementedLayerStoreServer) ReadLayer(context.Context, *ReadLayerRequest) (*ReadLayerResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ReadLayer not implemented")
}
func (UnimplementedLayerStoreServer) HasLayer(context.Context, *HasLayerRequest) (*HasLayerResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method HasLayer not implemented")
}
func (UnimplementedLayerStoreServer) HasImage(context.Context, *HasImageRequest) (*HasImageResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method HasImage not implemented")
}
func (UnimplementedLayerStoreServer) mustEmbedUnimplementedLayerStoreServer() {}
func (UnimplementedLayerStoreServer) testEmbeddedByValue()                    {}

// UnsafeLayerStoreServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to LayerStoreServer will
// result in compilation errors.
type UnsafeLayerStoreServer interface {
	mustEmbedUnimplementedLayerStoreServer()
}

func RegisterLayerStoreServer(s grpc.ServiceRegistrar, srv LayerStoreServer) {
	// If the following call pancis, it indicates UnimplementedLayerStoreServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&LayerStore_ServiceDesc, srv)
}

func _LayerStore_PullImage_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PullImageRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(LayerStoreServer).PullImage(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: LayerStore_PullImage_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(LayerStoreServer).PullImage(ctx, req.(*PullImageRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _LayerStore_StatLayer_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(StatLayerRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(LayerStoreServer).StatLayer(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: LayerStore_StatLayer_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(LayerStoreServer).StatLayer(ctx, req.(*StatLayerRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _LayerStore_ReadLayer_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ReadLayerRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(LayerStoreServer).ReadLayer(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: LayerStore_ReadLayer_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(LayerStoreServer).ReadLayer(ctx, req.(*ReadLayerRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _LayerStore_HasLayer_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(HasLayerRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(LayerStoreServer).HasLayer(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: LayerStore_HasLayer_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(LayerStoreServer).HasLayer(ctx, req.(*HasLayerRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _LayerStore_HasImage_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(HasImageRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(LayerStoreServer).HasImage(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: LayerStore_HasImage_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(LayerStoreServer).HasImage(ctx, req.(*HasImageRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// LayerStore_ServiceDesc is the grpc.ServiceDesc for LayerStore service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var LayerStore_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "layerstore.v1.LayerStore",
	HandlerType: (*LayerStoreServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "PullImage",
			Handler:    _LayerStore_PullImage_Handler,
		},
		{
			MethodName: "StatLayer",
			Handler:    _LayerStore_StatLayer_Handler,
		},
		{
			MethodName: "ReadLayer",
			Handler:    _LayerStore_ReadLayer_Handler,
		},
		{
			MethodName: "HasLayer",
			Handler:    _LayerStore_HasLayer_Handler,
		},
		{
			MethodName: "HasImage",
			Handler:    _LayerStore_HasImage_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "api/layerstore/v1/layerstore.proto",
}
