// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v4.24.2
// source: api/pagecache/v1/pagecache.proto

package pagecachepb

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	PageCacheService_PutPage_FullMethodName      = "/pagecache.v1.PageCacheService/PutPage"
	PageCacheService_GetPage_FullMethodName      = "/pagecache.v1.PageCacheService/GetPage"
	PageCacheService_Release_FullMethodName      = "/pagecache.v1.PageCacheService/Release"
	PageCacheService_BatchGetPage_FullMethodName = "/pagecache.v1.PageCacheService/BatchGetPage"
	PageCacheService_BatchRelease_FullMethodName = "/pagecache.v1.PageCacheService/BatchRelease"
	PageCacheService_Register_FullMethodName     = "/pagecache.v1.PageCacheService/Register"
	PageCacheService_GetStats_FullMethodName     = "/pagecache.v1.PageCacheService/GetStats"
)

// PageCacheServiceClient is the client API for PageCacheService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type PageCacheServiceClient interface {
	// Write a page to cache (client streaming for large pages).
	PutPage(ctx context.Context, opts ...grpc.CallOption) (grpc.ClientStreamingClient[PutPageChunk, PutPageResponse], error)
	// Read a page from cache. Returns disk location + lease on hit.
	GetPage(ctx context.Context, in *GetPageRequest, opts ...grpc.CallOption) (*GetPageResponse, error)
	// Release a lease, allowing the block to be evicted.
	Release(ctx context.Context, in *ReleaseRequest, opts ...grpc.CallOption) (*ReleaseResponse, error)
	// Batch read pages (reduces IPC roundtrips).
	BatchGetPage(ctx context.Context, in *BatchGetPageRequest, opts ...grpc.CallOption) (*BatchGetPageResponse, error)
	// Batch release leases.
	BatchRelease(ctx context.Context, in *BatchReleaseRequest, opts ...grpc.CallOption) (*BatchReleaseResponse, error)
	// Register client session for crash recovery.
	Register(ctx context.Context, in *RegisterRequest, opts ...grpc.CallOption) (*RegisterResponse, error)
	// Query cache statistics.
	GetStats(ctx context.Context, in *GetStatsRequest, opts ...grpc.CallOption) (*GetStatsResponse, error)
}

type pageCacheServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewPageCacheServiceClient(cc grpc.ClientConnInterface) PageCacheServiceClient {
	return &pageCacheServiceClient{cc}
}

func (c *pageCacheServiceClient) PutPage(ctx context.Context, opts ...grpc.CallOption) (grpc.ClientStreamingClient[PutPageChunk, PutPageResponse], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &PageCacheService_ServiceDesc.Streams[0], PageCacheService_PutPage_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[PutPageChunk, PutPageResponse]{ClientStream: stream}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type PageCacheService_PutPageClient = grpc.ClientStreamingClient[PutPageChunk, PutPageResponse]

func (c *pageCacheServiceClient) GetPage(ctx context.Context, in *GetPageRequest, opts ...grpc.CallOption) (*GetPageResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetPageResponse)
	err := c.cc.Invoke(ctx, PageCacheService_GetPage_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *pageCacheServiceClient) Release(ctx context.Context, in *ReleaseRequest, opts ...grpc.CallOption) (*ReleaseResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ReleaseResponse)
	err := c.cc.Invoke(ctx, PageCacheService_Release_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *pageCacheServiceClient) BatchGetPage(ctx context.Context, in *BatchGetPageRequest, opts ...grpc.CallOption) (*BatchGetPageResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(BatchGetPageResponse)
	err := c.cc.Invoke(ctx, PageCacheService_BatchGetPage_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *pageCacheServiceClient) BatchRelease(ctx context.Context, in *BatchReleaseRequest, opts ...grpc.CallOption) (*BatchReleaseResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(BatchReleaseResponse)
	err := c.cc.Invoke(ctx, PageCacheService_BatchRelease_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *pageCacheServiceClient) Register(ctx context.Context, in *RegisterRequest, opts ...grpc.CallOption) (*RegisterResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(RegisterResponse)
	err := c.cc.Invoke(ctx, PageCacheService_Register_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *pageCacheServiceClient) GetStats(ctx context.Context, in *GetStatsRequest, opts ...grpc.CallOption) (*GetStatsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetStatsResponse)
	err := c.cc.Invoke(ctx, PageCacheService_GetStats_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// PageCacheServiceServer is the server API for PageCacheService service.
// All implementations must embed UnimplementedPageCacheServiceServer
// for forward compatibility.
type PageCacheServiceServer interface {
	// Write a page to cache (client streaming for large pages).
	PutPage(grpc.ClientStreamingServer[PutPageChunk, PutPageResponse]) error
	// Read a page from cache. Returns disk location + lease on hit.
	GetPage(context.Context, *GetPageRequest) (*GetPageResponse, error)
	// Release a lease, allowing the block to be evicted.
	Release(context.Context, *ReleaseRequest) (*ReleaseResponse, error)
	// Batch read pages (reduces IPC roundtrips).
	BatchGetPage(context.Context, *BatchGetPageRequest) (*BatchGetPageResponse, error)
	// Batch release leases.
	BatchRelease(context.Context, *BatchReleaseRequest) (*BatchReleaseResponse, error)
	// Register client session for crash recovery.
	Register(context.Context, *RegisterRequest) (*RegisterResponse, error)
	// Query cache statistics.
	GetStats(context.Context, *GetStatsRequest) (*GetStatsResponse, error)
	mustEmbedUnimplementedPageCacheServiceServer()
}

// UnimplementedPageCacheServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedPageCacheServiceServer struct{}

func (UnimplementedPageCacheServiceServer) PutPage(grpc.ClientStreamingServer[PutPageChunk, PutPageResponse]) error {
	return status.Errorf(codes.Unimplemented, "method PutPage not implemented")
}
func (UnimplementedPageCacheServiceServer) GetPage(context.Context, *GetPageRequest) (*GetPageResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetPage not implemented")
}
func (UnimplementedPageCacheServiceServer) Release(context.Context, *ReleaseRequest) (*ReleaseResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Release not implemented")
}
func (UnimplementedPageCacheServiceServer) BatchGetPage(context.Context, *BatchGetPageRequest) (*BatchGetPageResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method BatchGetPage not implemented")
}
func (UnimplementedPageCacheServiceServer) BatchRelease(context.Context, *BatchReleaseRequest) (*BatchReleaseResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method BatchRelease not implemented")
}
func (UnimplementedPageCacheServiceServer) Register(context.Context, *RegisterRequest) (*RegisterResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Register not implemented")
}
func (UnimplementedPageCacheServiceServer) GetStats(context.Context, *GetStatsRequest) (*GetStatsResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetStats not implemented")
}
func (UnimplementedPageCacheServiceServer) mustEmbedUnimplementedPageCacheServiceServer() {}
func (UnimplementedPageCacheServiceServer) testEmbeddedByValue()                          {}

// UnsafePageCacheServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to PageCacheServiceServer will
// result in compilation errors.
type UnsafePageCacheServiceServer interface {
	mustEmbedUnimplementedPageCacheServiceServer()
}

func RegisterPageCacheServiceServer(s grpc.ServiceRegistrar, srv PageCacheServiceServer) {
	// If the following call pancis, it indicates UnimplementedPageCacheServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&PageCacheService_ServiceDesc, srv)
}

func _PageCacheService_PutPage_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(PageCacheServiceServer).PutPage(&grpc.GenericServerStream[PutPageChunk, PutPageResponse]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type PageCacheService_PutPageServer = grpc.ClientStreamingServer[PutPageChunk, PutPageResponse]

func _PageCacheService_GetPage_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetPageRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PageCacheServiceServer).GetPage(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: PageCacheService_GetPage_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PageCacheServiceServer).GetPage(ctx, req.(*GetPageRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _PageCacheService_Release_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ReleaseRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PageCacheServiceServer).Release(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: PageCacheService_Release_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PageCacheServiceServer).Release(ctx, req.(*ReleaseRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _PageCacheService_BatchGetPage_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(BatchGetPageRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PageCacheServiceServer).BatchGetPage(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: PageCacheService_BatchGetPage_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PageCacheServiceServer).BatchGetPage(ctx, req.(*BatchGetPageRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _PageCacheService_BatchRelease_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(BatchReleaseRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PageCacheServiceServer).BatchRelease(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: PageCacheService_BatchRelease_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PageCacheServiceServer).BatchRelease(ctx, req.(*BatchReleaseRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _PageCacheService_Register_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RegisterRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PageCacheServiceServer).Register(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: PageCacheService_Register_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PageCacheServiceServer).Register(ctx, req.(*RegisterRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _PageCacheService_GetStats_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetStatsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PageCacheServiceServer).GetStats(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: PageCacheService_GetStats_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PageCacheServiceServer).GetStats(ctx, req.(*GetStatsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// PageCacheService_ServiceDesc is the grpc.ServiceDesc for PageCacheService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var PageCacheService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "pagecache.v1.PageCacheService",
	HandlerType: (*PageCacheServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetPage",
			Handler:    _PageCacheService_GetPage_Handler,
		},
		{
			MethodName: "Release",
			Handler:    _PageCacheService_Release_Handler,
		},
		{
			MethodName: "BatchGetPage",
			Handler:    _PageCacheService_BatchGetPage_Handler,
		},
		{
			MethodName: "BatchRelease",
			Handler:    _PageCacheService_BatchRelease_Handler,
		},
		{
			MethodName: "Register",
			Handler:    _PageCacheService_Register_Handler,
		},
		{
			MethodName: "GetStats",
			Handler:    _PageCacheService_GetStats_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "PutPage",
			Handler:       _PageCacheService_PutPage_Handler,
			ClientStreams: true,
		},
	},
	Metadata: "api/pagecache/v1/pagecache.proto",
}
