// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.5
// 	protoc        v4.24.2
// source: api/pagecache/v1/pagecache.proto

package pagecachepb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type PutPageStatus int32

const (
	PutPageStatus_PUT_PAGE_OK             PutPageStatus = 0
	PutPageStatus_PUT_PAGE_ALREADY_EXISTS PutPageStatus = 1
	PutPageStatus_PUT_PAGE_NO_SPACE       PutPageStatus = 2
	PutPageStatus_PUT_PAGE_INVALID        PutPageStatus = 3
)

// Enum value maps for PutPageStatus.
var (
	PutPageStatus_name = map[int32]string{
		0: "PUT_PAGE_OK",
		1: "PUT_PAGE_ALREADY_EXISTS",
		2: "PUT_PAGE_NO_SPACE",
		3: "PUT_PAGE_INVALID",
	}
	PutPageStatus_value = map[string]int32{
		"PUT_PAGE_OK":             0,
		"PUT_PAGE_ALREADY_EXISTS": 1,
		"PUT_PAGE_NO_SPACE":       2,
		"PUT_PAGE_INVALID":        3,
	}
)

func (x PutPageStatus) Enum() *PutPageStatus {
	p := new(PutPageStatus)
	*p = x
	return p
}

func (x PutPageStatus) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (PutPageStatus) Descriptor() protoreflect.EnumDescriptor {
	return file_api_pagecache_v1_pagecache_proto_enumTypes[0].Descriptor()
}

func (PutPageStatus) Type() protoreflect.EnumType {
	return &file_api_pagecache_v1_pagecache_proto_enumTypes[0]
}

func (x PutPageStatus) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use PutPageStatus.Descriptor instead.
func (PutPageStatus) EnumDescriptor() ([]byte, []int) {
	return file_api_pagecache_v1_pagecache_proto_rawDescGZIP(), []int{0}
}

type GetPageStatus int32

const (
	GetPageStatus_CACHE_HIT  GetPageStatus = 0
	GetPageStatus_CACHE_MISS GetPageStatus = 1
)

// Enum value maps for GetPageStatus.
var (
	GetPageStatus_name = map[int32]string{
		0: "CACHE_HIT",
		1: "CACHE_MISS",
	}
	GetPageStatus_value = map[string]int32{
		"CACHE_HIT":  0,
		"CACHE_MISS": 1,
	}
)

func (x GetPageStatus) Enum() *GetPageStatus {
	p := new(GetPageStatus)
	*p = x
	return p
}

func (x GetPageStatus) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (GetPageStatus) Descriptor() protoreflect.EnumDescriptor {
	return file_api_pagecache_v1_pagecache_proto_enumTypes[1].Descriptor()
}

func (GetPageStatus) Type() protoreflect.EnumType {
	return &file_api_pagecache_v1_pagecache_proto_enumTypes[1]
}

func (x GetPageStatus) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use GetPageStatus.Descriptor instead.
func (GetPageStatus) EnumDescriptor() ([]byte, []int) {
	return file_api_pagecache_v1_pagecache_proto_rawDescGZIP(), []int{1}
}

type PutPageChunk struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Header        *PutPageHeader         `protobuf:"bytes,1,opt,name=header,proto3" json:"header,omitempty"` // Only in first chunk of stream
	Data          []byte                 `protobuf:"bytes,2,opt,name=data,proto3" json:"data,omitempty"`     // Data fragment, recommended ≤64KB
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PutPageChunk) Reset() {
	*x = PutPageChunk{}
	mi := &file_api_pagecache_v1_pagecache_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PutPageChunk) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PutPageChunk) ProtoMessage() {}

func (x *PutPageChunk) ProtoReflect() protoreflect.Message {
	mi := &file_api_pagecache_v1_pagecache_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PutPageChunk.ProtoReflect.Descriptor instead.
func (*PutPageChunk) Descriptor() ([]byte, []int) {
	return file_api_pagecache_v1_pagecache_proto_rawDescGZIP(), []int{0}
}

func (x *PutPageChunk) GetHeader() *PutPageHeader {
	if x != nil {
		return x.Header
	}
	return nil
}

func (x *PutPageChunk) GetData() []byte {
	if x != nil {
		return x.Data
	}
	return nil
}

type PutPageHeader struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Digest        string                 `protobuf:"bytes,1,opt,name=digest,proto3" json:"digest,omitempty"`                         // Content digest, e.g. "sha256:af3b..."
	PageId        uint64                 `protobuf:"varint,2,opt,name=page_id,json=pageId,proto3" json:"page_id,omitempty"`          // Page number within the file
	TotalSize     uint32                 `protobuf:"varint,3,opt,name=total_size,json=totalSize,proto3" json:"total_size,omitempty"` // Total page size in bytes (for slab allocation)
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PutPageHeader) Reset() {
	*x = PutPageHeader{}
	mi := &file_api_pagecache_v1_pagecache_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PutPageHeader) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PutPageHeader) ProtoMessage() {}

func (x *PutPageHeader) ProtoReflect() protoreflect.Message {
	mi := &file_api_pagecache_v1_pagecache_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PutPageHeader.ProtoReflect.Descriptor instead.
func (*PutPageHeader) Descriptor() ([]byte, []int) {
	return file_api_pagecache_v1_pagecache_proto_rawDescGZIP(), []int{1}
}

func (x *PutPageHeader) GetDigest() string {
	if x != nil {
		return x.Digest
	}
	return ""
}

func (x *PutPageHeader) GetPageId() uint64 {
	if x != nil {
		return x.PageId
	}
	return 0
}

func (x *PutPageHeader) GetTotalSize() uint32 {
	if x != nil {
		return x.TotalSize
	}
	return 0
}

type PutPageResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Status        PutPageStatus          `protobuf:"varint,1,opt,name=status,proto3,enum=pagecache.v1.PutPageStatus" json:"status,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PutPageResponse) Reset() {
	*x = PutPageResponse{}
	mi := &file_api_pagecache_v1_pagecache_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PutPageResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PutPageResponse) ProtoMessage() {}

func (x *PutPageResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_pagecache_v1_pagecache_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PutPageResponse.ProtoReflect.Descriptor instead.
func (*PutPageResponse) Descriptor() ([]byte, []int) {
	return file_api_pagecache_v1_pagecache_proto_rawDescGZIP(), []int{2}
}

func (x *PutPageResponse) GetStatus() PutPageStatus {
	if x != nil {
		return x.Status
	}
	return PutPageStatus_PUT_PAGE_OK
}

type GetPageRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Digest        string                 `protobuf:"bytes,1,opt,name=digest,proto3" json:"digest,omitempty"`
	PageId        uint64                 `protobuf:"varint,2,opt,name=page_id,json=pageId,proto3" json:"page_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetPageRequest) Reset() {
	*x = GetPageRequest{}
	mi := &file_api_pagecache_v1_pagecache_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetPageRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetPageRequest) ProtoMessage() {}

func (x *GetPageRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_pagecache_v1_pagecache_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetPageRequest.ProtoReflect.Descriptor instead.
func (*GetPageRequest) Descriptor() ([]byte, []int) {
	return file_api_pagecache_v1_pagecache_proto_rawDescGZIP(), []int{3}
}

func (x *GetPageRequest) GetDigest() string {
	if x != nil {
		return x.Digest
	}
	return ""
}

func (x *GetPageRequest) GetPageId() uint64 {
	if x != nil {
		return x.PageId
	}
	return 0
}

type GetPageResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Status        GetPageStatus          `protobuf:"varint,1,opt,name=status,proto3,enum=pagecache.v1.GetPageStatus" json:"status,omitempty"`
	CacheFilePath string                 `protobuf:"bytes,2,opt,name=cache_file_path,json=cacheFilePath,proto3" json:"cache_file_path,omitempty"` // Chunk file path on disk
	CacheOffset   uint64                 `protobuf:"varint,3,opt,name=cache_offset,json=cacheOffset,proto3" json:"cache_offset,omitempty"`        // Byte offset within chunk file
	DataSize      uint32                 `protobuf:"varint,4,opt,name=data_size,json=dataSize,proto3" json:"data_size,omitempty"`                 // Actual data size
	LeaseId       uint64                 `protobuf:"varint,5,opt,name=lease_id,json=leaseId,proto3" json:"lease_id,omitempty"`                    // Lease ID for subsequent Release
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetPageResponse) Reset() {
	*x = GetPageResponse{}
	mi := &file_api_pagecache_v1_pagecache_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetPageResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetPageResponse) ProtoMessage() {}

func (x *GetPageResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_pagecache_v1_pagecache_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetPageResponse.ProtoReflect.Descriptor instead.
func (*GetPageResponse) Descriptor() ([]byte, []int) {
	return file_api_pagecache_v1_pagecache_proto_rawDescGZIP(), []int{4}
}

func (x *GetPageResponse) GetStatus() GetPageStatus {
	if x != nil {
		return x.Status
	}
	return GetPageStatus_CACHE_HIT
}

func (x *GetPageResponse) GetCacheFilePath() string {
	if x != nil {
		return x.CacheFilePath
	}
	return ""
}

func (x *GetPageResponse) GetCacheOffset() uint64 {
	if x != nil {
		return x.CacheOffset
	}
	return 0
}

func (x *GetPageResponse) GetDataSize() uint32 {
	if x != nil {
		return x.DataSize
	}
	return 0
}

func (x *GetPageResponse) GetLeaseId() uint64 {
	if x != nil {
		return x.LeaseId
	}
	return 0
}

type ReleaseRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	LeaseId       uint64                 `protobuf:"varint,1,opt,name=lease_id,json=leaseId,proto3" json:"lease_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ReleaseRequest) Reset() {
	*x = ReleaseRequest{}
	mi := &file_api_pagecache_v1_pagecache_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReleaseRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReleaseRequest) ProtoMessage() {}

func (x *ReleaseRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_pagecache_v1_pagecache_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReleaseRequest.ProtoReflect.Descriptor instead.
func (*ReleaseRequest) Descriptor() ([]byte, []int) {
	return file_api_pagecache_v1_pagecache_proto_rawDescGZIP(), []int{5}
}

func (x *ReleaseRequest) GetLeaseId() uint64 {
	if x != nil {
		return x.LeaseId
	}
	return 0
}

type ReleaseResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ReleaseResponse) Reset() {
	*x = ReleaseResponse{}
	mi := &file_api_pagecache_v1_pagecache_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReleaseResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReleaseResponse) ProtoMessage() {}

func (x *ReleaseResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_pagecache_v1_pagecache_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReleaseResponse.ProtoReflect.Descriptor instead.
func (*ReleaseResponse) Descriptor() ([]byte, []int) {
	return file_api_pagecache_v1_pagecache_proto_rawDescGZIP(), []int{6}
}

type BatchGetPageRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Pages         []*GetPageRequest      `protobuf:"bytes,1,rep,name=pages,proto3" json:"pages,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BatchGetPageRequest) Reset() {
	*x = BatchGetPageRequest{}
	mi := &file_api_pagecache_v1_pagecache_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BatchGetPageRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BatchGetPageRequest) ProtoMessage() {}

func (x *BatchGetPageRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_pagecache_v1_pagecache_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BatchGetPageRequest.ProtoReflect.Descriptor instead.
func (*BatchGetPageRequest) Descriptor() ([]byte, []int) {
	return file_api_pagecache_v1_pagecache_proto_rawDescGZIP(), []int{7}
}

func (x *BatchGetPageRequest) GetPages() []*GetPageRequest {
	if x != nil {
		return x.Pages
	}
	return nil
}

type BatchGetPageResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Pages         []*GetPageResponse     `protobuf:"bytes,1,rep,name=pages,proto3" json:"pages,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BatchGetPageResponse) Reset() {
	*x = BatchGetPageResponse{}
	mi := &file_api_pagecache_v1_pagecache_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BatchGetPageResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BatchGetPageResponse) ProtoMessage() {}

func (x *BatchGetPageResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_pagecache_v1_pagecache_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BatchGetPageResponse.ProtoReflect.Descriptor instead.
func (*BatchGetPageResponse) Descriptor() ([]byte, []int) {
	return file_api_pagecache_v1_pagecache_proto_rawDescGZIP(), []int{8}
}

func (x *BatchGetPageResponse) GetPages() []*GetPageResponse {
	if x != nil {
		return x.Pages
	}
	return nil
}

type BatchReleaseRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	LeaseIds      []uint64               `protobuf:"varint,1,rep,packed,name=lease_ids,json=leaseIds,proto3" json:"lease_ids,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BatchReleaseRequest) Reset() {
	*x = BatchReleaseRequest{}
	mi := &file_api_pagecache_v1_pagecache_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BatchReleaseRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BatchReleaseRequest) ProtoMessage() {}

func (x *BatchReleaseRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_pagecache_v1_pagecache_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BatchReleaseRequest.ProtoReflect.Descriptor instead.
func (*BatchReleaseRequest) Descriptor() ([]byte, []int) {
	return file_api_pagecache_v1_pagecache_proto_rawDescGZIP(), []int{9}
}

func (x *BatchReleaseRequest) GetLeaseIds() []uint64 {
	if x != nil {
		return x.LeaseIds
	}
	return nil
}

type BatchReleaseResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BatchReleaseResponse) Reset() {
	*x = BatchReleaseResponse{}
	mi := &file_api_pagecache_v1_pagecache_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BatchReleaseResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BatchReleaseResponse) ProtoMessage() {}

func (x *BatchReleaseResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_pagecache_v1_pagecache_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BatchReleaseResponse.ProtoReflect.Descriptor instead.
func (*BatchReleaseResponse) Descriptor() ([]byte, []int) {
	return file_api_pagecache_v1_pagecache_proto_rawDescGZIP(), []int{10}
}

type RegisterRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ClientId      string                 `protobuf:"bytes,1,opt,name=client_id,json=clientId,proto3" json:"client_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RegisterRequest) Reset() {
	*x = RegisterRequest{}
	mi := &file_api_pagecache_v1_pagecache_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RegisterRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RegisterRequest) ProtoMessage() {}

func (x *RegisterRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_pagecache_v1_pagecache_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RegisterRequest.ProtoReflect.Descriptor instead.
func (*RegisterRequest) Descriptor() ([]byte, []int) {
	return file_api_pagecache_v1_pagecache_proto_rawDescGZIP(), []int{11}
}

func (x *RegisterRequest) GetClientId() string {
	if x != nil {
		return x.ClientId
	}
	return ""
}

type RegisterResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SessionId     string                 `protobuf:"bytes,1,opt,name=session_id,json=sessionId,proto3" json:"session_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RegisterResponse) Reset() {
	*x = RegisterResponse{}
	mi := &file_api_pagecache_v1_pagecache_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RegisterResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RegisterResponse) ProtoMessage() {}

func (x *RegisterResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_pagecache_v1_pagecache_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RegisterResponse.ProtoReflect.Descriptor instead.
func (*RegisterResponse) Descriptor() ([]byte, []int) {
	return file_api_pagecache_v1_pagecache_proto_rawDescGZIP(), []int{12}
}

func (x *RegisterResponse) GetSessionId() string {
	if x != nil {
		return x.SessionId
	}
	return ""
}

type GetStatsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetStatsRequest) Reset() {
	*x = GetStatsRequest{}
	mi := &file_api_pagecache_v1_pagecache_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetStatsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetStatsRequest) ProtoMessage() {}

func (x *GetStatsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_pagecache_v1_pagecache_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetStatsRequest.ProtoReflect.Descriptor instead.
func (*GetStatsRequest) Descriptor() ([]byte, []int) {
	return file_api_pagecache_v1_pagecache_proto_rawDescGZIP(), []int{13}
}

type GetStatsResponse struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	TotalPages       uint64                 `protobuf:"varint,1,opt,name=total_pages,json=totalPages,proto3" json:"total_pages,omitempty"`
	TotalBytes       uint64                 `protobuf:"varint,2,opt,name=total_bytes,json=totalBytes,proto3" json:"total_bytes,omitempty"`
	MaxBytes         uint64                 `protobuf:"varint,3,opt,name=max_bytes,json=maxBytes,proto3" json:"max_bytes,omitempty"`
	HitCount         uint64                 `protobuf:"varint,4,opt,name=hit_count,json=hitCount,proto3" json:"hit_count,omitempty"`
	MissCount        uint64                 `protobuf:"varint,5,opt,name=miss_count,json=missCount,proto3" json:"miss_count,omitempty"`
	ActiveLeases     uint32                 `protobuf:"varint,6,opt,name=active_leases,json=activeLeases,proto3" json:"active_leases,omitempty"`
	ConnectedClients uint32                 `protobuf:"varint,7,opt,name=connected_clients,json=connectedClients,proto3" json:"connected_clients,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *GetStatsResponse) Reset() {
	*x = GetStatsResponse{}
	mi := &file_api_pagecache_v1_pagecache_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetStatsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetStatsResponse) ProtoMessage() {}

func (x *GetStatsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_pagecache_v1_pagecache_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetStatsResponse.ProtoReflect.Descriptor instead.
func (*GetStatsResponse) Descriptor() ([]byte, []int) {
	return file_api_pagecache_v1_pagecache_proto_rawDescGZIP(), []int{14}
}

func (x *GetStatsResponse) GetTotalPages() uint64 {
	if x != nil {
		return x.TotalPages
	}
	return 0
}

func (x *GetStatsResponse) GetTotalBytes() uint64 {
	if x != nil {
		return x.TotalBytes
	}
	return 0
}

func (x *GetStatsResponse) GetMaxBytes() uint64 {
	if x != nil {
		return x.MaxBytes
	}
	return 0
}

func (x *GetStatsResponse) GetHitCount() uint64 {
	if x != nil {
		return x.HitCount
	}
	return 0
}

func (x *GetStatsResponse) GetMissCount() uint64 {
	if x != nil {
		return x.MissCount
	}
	return 0
}

func (x *GetStatsResponse) GetActiveLeases() uint32 {
	if x != nil {
		return x.ActiveLeases
	}
	return 0
}

func (x *GetStatsResponse) GetConnectedClients() uint32 {
	if x != nil {
		return x.ConnectedClients
	}
	return 0
}

var File_api_pagecache_v1_pagecache_proto protoreflect.FileDescriptor

var file_api_pagecache_v1_pagecache_proto_rawDesc = string([]byte{
	0x0a, 0x20, 0x61, 0x70, 0x69, 0x2f, 0x70, 0x61, 0x67, 0x65, 0x63, 0x61, 0x63, 0x68, 0x65, 0x2f,
	0x76, 0x31, 0x2f, 0x70, 0x61, 0x67, 0x65, 0x63, 0x61, 0x63, 0x68, 0x65, 0x2e, 0x70, 0x72, 0x6f,
	0x74, 0x6f, 0x12, 0x0c, 0x70, 0x61, 0x67, 0x65, 0x63, 0x61, 0x63, 0x68, 0x65, 0x2e, 0x76, 0x31,
	0x22, 0x57, 0x0a, 0x0c, 0x50, 0x75, 0x74, 0x50, 0x61, 0x67, 0x65, 0x43, 0x68, 0x75, 0x6e, 0x6b,
	0x12, 0x33, 0x0a, 0x06, 0x68, 0x65, 0x61, 0x64, 0x65, 0x72, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b,
	0x32, 0x1b, 0x2e, 0x70, 0x61, 0x67, 0x65, 0x63, 0x61, 0x63, 0x68, 0x65, 0x2e, 0x76, 0x31, 0x2e,
	0x50, 0x75, 0x74, 0x50, 0x61, 0x67, 0x65, 0x48, 0x65, 0x61, 0x64, 0x65, 0x72, 0x52, 0x06, 0x68,
	0x65, 0x61, 0x64, 0x65, 0x72, 0x12, 0x12, 0x0a, 0x04, 0x64, 0x61, 0x74, 0x61, 0x18, 0x02, 0x20,
	0x01, 0x28, 0x0c, 0x52, 0x04, 0x64, 0x61, 0x74, 0x61, 0x22, 0x5f, 0x0a, 0x0d, 0x50, 0x75, 0x74,
	0x50, 0x61, 0x67, 0x65, 0x48, 0x65, 0x61, 0x64, 0x65, 0x72, 0x12, 0x16, 0x0a, 0x06, 0x64, 0x69,
	0x67, 0x65, 0x73, 0x74, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x64, 0x69, 0x67, 0x65,
	0x73, 0x74, 0x12, 0x17, 0x0a, 0x07, 0x70, 0x61, 0x67, 0x65, 0x5f, 0x69, 0x64, 0x18, 0x02, 0x20,
	0x01, 0x28, 0x04, 0x52, 0x06, 0x70, 0x61, 0x67, 0x65, 0x49, 0x64, 0x12, 0x1d, 0x0a, 0x0a, 0x74,
	0x6f, 0x74, 0x61, 0x6c, 0x5f, 0x73, 0x69, 0x7a, 0x65, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0d, 0x52,
	0x09, 0x74, 0x6f, 0x74, 0x61, 0x6c, 0x53, 0x69, 0x7a, 0x65, 0x22, 0x46, 0x0a, 0x0f, 0x50, 0x75,
	0x74, 0x50, 0x61, 0x67, 0x65, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x33, 0x0a,
	0x06, 0x73, 0x74, 0x61, 0x74, 0x75, 0x73, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x1b, 0x2e,
	0x70, 0x61, 0x67, 0x65, 0x63, 0x61, 0x63, 0x68, 0x65, 0x2e, 0x76, 0x31, 0x2e, 0x50, 0x75, 0x74,
	0x50, 0x61, 0x67, 0x65, 0x53, 0x74, 0x61, 0x74, 0x75, 0x73, 0x52, 0x06, 0x73, 0x74, 0x61, 0x74,
	0x75, 0x73, 0x22, 0x41, 0x0a, 0x0e, 0x47, 0x65, 0x74, 0x50, 0x61, 0x67, 0x65, 0x52, 0x65, 0x71,
	0x75, 0x65, 0x73, 0x74, 0x12, 0x16, 0x0a, 0x06, 0x64, 0x69, 0x67, 0x65, 0x73, 0x74, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x64, 0x69, 0x67, 0x65, 0x73, 0x74, 0x12, 0x17, 0x0a, 0x07,
	0x70, 0x61, 0x67, 0x65, 0x5f, 0x69, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x04, 0x52, 0x06, 0x70,
	0x61, 0x67, 0x65, 0x49, 0x64, 0x22, 0xc9, 0x01, 0x0a, 0x0f, 0x47, 0x65, 0x74, 0x50, 0x61, 0x67,
	0x65, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x33, 0x0a, 0x06, 0x73, 0x74, 0x61,
	0x74, 0x75, 0x73, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x1b, 0x2e, 0x70, 0x61, 0x67, 0x65,
	0x63, 0x61, 0x63, 0x68, 0x65, 0x2e, 0x76, 0x31, 0x2e, 0x47, 0x65, 0x74, 0x50, 0x61, 0x67, 0x65,
	0x53, 0x74, 0x61, 0x74, 0x75, 0x73, 0x52, 0x06, 0x73, 0x74, 0x61, 0x74, 0x75, 0x73, 0x12, 0x26,
	0x0a, 0x0f, 0x63, 0x61, 0x63, 0x68, 0x65, 0x5f, 0x66, 0x69, 0x6c, 0x65, 0x5f, 0x70, 0x61, 0x74,
	0x68, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0d, 0x63, 0x61, 0x63, 0x68, 0x65, 0x46, 0x69,
	0x6c, 0x65, 0x50, 0x61, 0x74, 0x68, 0x12, 0x21, 0x0a, 0x0c, 0x63, 0x61, 0x63, 0x68, 0x65, 0x5f,
	0x6f, 0x66, 0x66, 0x73, 0x65, 0x74, 0x18, 0x03, 0x20, 0x01, 0x28, 0x04, 0x52, 0x0b, 0x63, 0x61,
	0x63, 0x68, 0x65, 0x4f, 0x66, 0x66, 0x73, 0x65, 0x74, 0x12, 0x1b, 0x0a, 0x09, 0x64, 0x61, 0x74,
	0x61, 0x5f, 0x73, 0x69, 0x7a, 0x65, 0x18, 0x04, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x08, 0x64, 0x61,
	0x74, 0x61, 0x53, 0x69, 0x7a, 0x65, 0x12, 0x19, 0x0a, 0x08, 0x6c, 0x65, 0x61, 0x73, 0x65, 0x5f,
	0x69, 0x64, 0x18, 0x05, 0x20, 0x01, 0x28, 0x04, 0x52, 0x07, 0x6c, 0x65, 0x61, 0x73, 0x65, 0x49,
	0x64, 0x22, 0x2b, 0x0a, 0x0e, 0x52, 0x65, 0x6c, 0x65, 0x61, 0x73, 0x65, 0x52, 0x65, 0x71, 0x75,
	0x65, 0x73, 0x74, 0x12, 0x19, 0x0a, 0x08, 0x6c, 0x65, 0x61, 0x73, 0x65, 0x5f, 0x69, 0x64, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x04, 0x52, 0x07, 0x6c, 0x65, 0x61, 0x73, 0x65, 0x49, 0x64, 0x22, 0x11,
	0x0a, 0x0f, 0x52, 0x65, 0x6c, 0x65, 0x61, 0x73, 0x65, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73,
	0x65, 0x22, 0x49, 0x0a, 0x13, 0x42, 0x61, 0x74, 0x63, 0x68, 0x47, 0x65, 0x74, 0x50, 0x61, 0x67,
	0x65, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x32, 0x0a, 0x05, 0x70, 0x61, 0x67, 0x65,
	0x73, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x1c, 0x2e, 0x70, 0x61, 0x67, 0x65, 0x63, 0x61,
	0x63, 0x68, 0x65, 0x2e, 0x76, 0x31, 0x2e, 0x47, 0x65, 0x74, 0x50, 0x61, 0x67, 0x65, 0x52, 0x65,
	0x71, 0x75, 0x65, 0x73, 0x74, 0x52, 0x05, 0x70, 0x61, 0x67, 0x65, 0x73, 0x22, 0x4b, 0x0a, 0x14,
	0x42, 0x61, 0x74, 0x63, 0x68, 0x47, 0x65, 0x74, 0x50, 0x61, 0x67, 0x65, 0x52, 0x65, 0x73, 0x70,
	0x6f, 0x6e, 0x73, 0x65, 0x12, 0x33, 0x0a, 0x05, 0x70, 0x61, 0x67, 0x65, 0x73, 0x18, 0x01, 0x20,
	0x03, 0x28, 0x0b, 0x32, 0x1d, 0x2e, 0x70, 0x61, 0x67, 0x65, 0x63, 0x61, 0x63, 0x68, 0x65, 0x2e,
	0x76, 0x31, 0x2e, 0x47, 0x65, 0x74, 0x50, 0x61, 0x67, 0x65, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e,
	0x73, 0x65, 0x52, 0x05, 0x70, 0x61, 0x67, 0x65, 0x73, 0x22, 0x32, 0x0a, 0x13, 0x42, 0x61, 0x74,
	0x63, 0x68, 0x52, 0x65, 0x6c, 0x65, 0x61, 0x73, 0x65, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74,
	0x12, 0x1b, 0x0a, 0x09, 0x6c, 0x65, 0x61, 0x73, 0x65, 0x5f, 0x69, 0x64, 0x73, 0x18, 0x01, 0x20,
	0x03, 0x28, 0x04, 0x52, 0x08, 0x6c, 0x65, 0x61, 0x73, 0x65, 0x49, 0x64, 0x73, 0x22, 0x16, 0x0a,
	0x14, 0x42, 0x61, 0x74, 0x63, 0x68, 0x52, 0x65, 0x6c, 0x65, 0x61, 0x73, 0x65, 0x52, 0x65, 0x73,
	0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x2e, 0x0a, 0x0f, 0x52, 0x65, 0x67, 0x69, 0x73, 0x74, 0x65,
	0x72, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x1b, 0x0a, 0x09, 0x63, 0x6c, 0x69, 0x65,
	0x6e, 0x74, 0x5f, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x63, 0x6c, 0x69,
	0x65, 0x6e, 0x74, 0x49, 0x64, 0x22, 0x31, 0x0a, 0x10, 0x52, 0x65, 0x67, 0x69, 0x73, 0x74, 0x65,
	0x72, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x1d, 0x0a, 0x0a, 0x73, 0x65, 0x73,
	0x73, 0x69, 0x6f, 0x6e, 0x5f, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x09, 0x73,
	0x65, 0x73, 0x73, 0x69, 0x6f, 0x6e, 0x49, 0x64, 0x22, 0x11, 0x0a, 0x0f, 0x47, 0x65, 0x74, 0x53,
	0x74, 0x61, 0x74, 0x73, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x22, 0xff, 0x01, 0x0a, 0x10,
	0x47, 0x65, 0x74, 0x53, 0x74, 0x61, 0x74, 0x73, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65,
	0x12, 0x1f, 0x0a, 0x0b, 0x74, 0x6f, 0x74, 0x61, 0x6c, 0x5f, 0x70, 0x61, 0x67, 0x65, 0x73, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x04, 0x52, 0x0a, 0x74, 0x6f, 0x74, 0x61, 0x6c, 0x50, 0x61, 0x67, 0x65,
	0x73, 0x12, 0x1f, 0x0a, 0x0b, 0x74, 0x6f, 0x74, 0x61, 0x6c, 0x5f, 0x62, 0x79, 0x74, 0x65, 0x73,
	0x18, 0x02, 0x20, 0x01, 0x28, 0x04, 0x52, 0x0a, 0x74, 0x6f, 0x74, 0x61, 0x6c, 0x42, 0x79, 0x74,
	0x65, 0x73, 0x12, 0x1b, 0x0a, 0x09, 0x6d, 0x61, 0x78, 0x5f, 0x62, 0x79, 0x74, 0x65, 0x73, 0x18,
	0x03, 0x20, 0x01, 0x28, 0x04, 0x52, 0x08, 0x6d, 0x61, 0x78, 0x42, 0x79, 0x74, 0x65, 0x73, 0x12,
	0x1b, 0x0a, 0x09, 0x68, 0x69, 0x74, 0x5f, 0x63, 0x6f, 0x75, 0x6e, 0x74, 0x18, 0x04, 0x20, 0x01,
	0x28, 0x04, 0x52, 0x08, 0x68, 0x69, 0x74, 0x43, 0x6f, 0x75, 0x6e, 0x74, 0x12, 0x1d, 0x0a, 0x0a,
	0x6d, 0x69, 0x73, 0x73, 0x5f, 0x63, 0x6f, 0x75, 0x6e, 0x74, 0x18, 0x05, 0x20, 0x01, 0x28, 0x04,
	0x52, 0x09, 0x6d, 0x69, 0x73, 0x73, 0x43, 0x6f, 0x75, 0x6e, 0x74, 0x12, 0x23, 0x0a, 0x0d, 0x61,
	0x63, 0x74, 0x69, 0x76, 0x65, 0x5f, 0x6c, 0x65, 0x61, 0x73, 0x65, 0x73, 0x18, 0x06, 0x20, 0x01,
	0x28, 0x0d, 0x52, 0x0c, 0x61, 0x63, 0x74, 0x69, 0x76, 0x65, 0x4c, 0x65, 0x61, 0x73, 0x65, 0x73,
	0x12, 0x2b, 0x0a, 0x11, 0x63, 0x6f, 0x6e, 0x6e, 0x65, 0x63, 0x74, 0x65, 0x64, 0x5f, 0x63, 0x6c,
	0x69, 0x65, 0x6e, 0x74, 0x73, 0x18, 0x07, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x10, 0x63, 0x6f, 0x6e,
	0x6e, 0x65, 0x63, 0x74, 0x65, 0x64, 0x43, 0x6c, 0x69, 0x65, 0x6e, 0x74, 0x73, 0x2a, 0x6a, 0x0a,
	0x0d, 0x50, 0x75, 0x74, 0x50, 0x61, 0x67, 0x65, 0x53, 0x74, 0x61, 0x74, 0x75, 0x73, 0x12, 0x0f,
	0x0a, 0x0b, 0x50, 0x55, 0x54, 0x5f, 0x50, 0x41, 0x47, 0x45, 0x5f, 0x4f, 0x4b, 0x10, 0x00, 0x12,
	0x1b, 0x0a, 0x17, 0x50, 0x55, 0x54, 0x5f, 0x50, 0x41, 0x47, 0x45, 0x5f, 0x41, 0x4c, 0x52, 0x45,
	0x41, 0x44, 0x59, 0x5f, 0x45, 0x58, 0x49, 0x53, 0x54, 0x53, 0x10, 0x01, 0x12, 0x15, 0x0a, 0x11,
	0x50, 0x55, 0x54, 0x5f, 0x50, 0x41, 0x47, 0x45, 0x5f, 0x4e, 0x4f, 0x5f, 0x53, 0x50, 0x41, 0x43,
	0x45, 0x10, 0x02, 0x12, 0x14, 0x0a, 0x10, 0x50, 0x55, 0x54, 0x5f, 0x50, 0x41, 0x47, 0x45, 0x5f,
	0x49, 0x4e, 0x56, 0x41, 0x4c, 0x49, 0x44, 0x10, 0x03, 0x2a, 0x2e, 0x0a, 0x0d, 0x47, 0x65, 0x74,
	0x50, 0x61, 0x67, 0x65, 0x53, 0x74, 0x61, 0x74, 0x75, 0x73, 0x12, 0x0d, 0x0a, 0x09, 0x43, 0x41,
	0x43, 0x48, 0x45, 0x5f, 0x48, 0x49, 0x54, 0x10, 0x00, 0x12, 0x0e, 0x0a, 0x0a, 0x43, 0x41, 0x43,
	0x48, 0x45, 0x5f, 0x4d, 0x49, 0x53, 0x53, 0x10, 0x01, 0x32, 0xae, 0x04, 0x0a, 0x10, 0x50, 0x61,
	0x67, 0x65, 0x43, 0x61, 0x63, 0x68, 0x65, 0x53, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x12, 0x46,
	0x0a, 0x07, 0x50, 0x75, 0x74, 0x50, 0x61, 0x67, 0x65, 0x12, 0x1a, 0x2e, 0x70, 0x61, 0x67, 0x65,
	0x63, 0x61, 0x63, 0x68, 0x65, 0x2e, 0x76, 0x31, 0x2e, 0x50, 0x75, 0x74, 0x50, 0x61, 0x67, 0x65,
	0x43, 0x68, 0x75, 0x6e, 0x6b, 0x1a, 0x1d, 0x2e, 0x70, 0x61, 0x67, 0x65, 0x63, 0x61, 0x63, 0x68,
	0x65, 0x2e, 0x76, 0x31, 0x2e, 0x50, 0x75, 0x74, 0x50, 0x61, 0x67, 0x65, 0x52, 0x65, 0x73, 0x70,
	0x6f, 0x6e, 0x73, 0x65, 0x28, 0x01, 0x12, 0x46, 0x0a, 0x07, 0x47, 0x65, 0x74, 0x50, 0x61, 0x67,
	0x65, 0x12, 0x1c, 0x2e, 0x70, 0x61, 0x67, 0x65, 0x63, 0x61, 0x63, 0x68, 0x65, 0x2e, 0x76, 0x31,
	0x2e, 0x47, 0x65, 0x74, 0x50, 0x61, 0x67, 0x65, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a,
	0x1d, 0x2e, 0x70, 0x61, 0x67, 0x65, 0x63, 0x61, 0x63, 0x68, 0x65, 0x2e, 0x76, 0x31, 0x2e, 0x47,
	0x65, 0x74, 0x50, 0x61, 0x67, 0x65, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x46,
	0x0a, 0x07, 0x52, 0x65, 0x6c, 0x65, 0x61, 0x73, 0x65, 0x12, 0x1c, 0x2e, 0x70, 0x61, 0x67, 0x65,
	0x63, 0x61, 0x63, 0x68, 0x65, 0x2e, 0x76, 0x31, 0x2e, 0x52, 0x65, 0x6c, 0x65, 0x61, 0x73, 0x65,
	0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x1d, 0x2e, 0x70, 0x61, 0x67, 0x65, 0x63, 0x61,
	0x63, 0x68, 0x65, 0x2e, 0x76, 0x31, 0x2e, 0x52, 0x65, 0x6c, 0x65, 0x61, 0x73, 0x65, 0x52, 0x65,
	0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x55, 0x0a, 0x0c, 0x42, 0x61, 0x74, 0x63, 0x68, 0x47,
	0x65, 0x74, 0x50, 0x61, 0x67, 0x65, 0x12, 0x21, 0x2e, 0x70, 0x61, 0x67, 0x65, 0x63, 0x61, 0x63,
	0x68, 0x65, 0x2e, 0x76, 0x31, 0x2e, 0x42, 0x61, 0x74, 0x63, 0x68, 0x47, 0x65, 0x74, 0x50, 0x61,
	0x67, 0x65, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x22, 0x2e, 0x70, 0x61, 0x67, 0x65,
	0x63, 0x61, 0x63, 0x68, 0x65, 0x2e, 0x76, 0x31, 0x2e, 0x42, 0x61, 0x74, 0x63, 0x68, 0x47, 0x65,
	0x74, 0x50, 0x61, 0x67, 0x65, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x55, 0x0a,
	0x0c, 0x42, 0x61, 0x74, 0x63, 0x68, 0x52, 0x65, 0x6c, 0x65, 0x61, 0x73, 0x65, 0x12, 0x21, 0x2e,
	0x70, 0x61, 0x67, 0x65, 0x63, 0x61, 0x63, 0x68, 0x65, 0x2e, 0x76, 0x31, 0x2e, 0x42, 0x61, 0x74,
	0x63, 0x68, 0x52, 0x65, 0x6c, 0x65, 0x61, 0x73, 0x65, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74,
	0x1a, 0x22, 0x2e, 0x70, 0x61, 0x67, 0x65, 0x63, 0x61, 0x63, 0x68, 0x65, 0x2e, 0x76, 0x31, 0x2e,
	0x42, 0x61, 0x74, 0x63, 0x68, 0x52, 0x65, 0x6c, 0x65, 0x61, 0x73, 0x65, 0x52, 0x65, 0x73, 0x70,
	0x6f, 0x6e, 0x73, 0x65, 0x12, 0x49, 0x0a, 0x08, 0x52, 0x65, 0x67, 0x69, 0x73, 0x74, 0x65, 0x72,
	0x12, 0x1d, 0x2e, 0x70, 0x61, 0x67, 0x65, 0x63, 0x61, 0x63, 0x68, 0x65, 0x2e, 0x76, 0x31, 0x2e,
	0x52, 0x65, 0x67, 0x69, 0x73, 0x74, 0x65, 0x72, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a,
	0x1e, 0x2e, 0x70, 0x61, 0x67, 0x65, 0x63, 0x61, 0x63, 0x68, 0x65, 0x2e, 0x76, 0x31, 0x2e, 0x52,
	0x65, 0x67, 0x69, 0x73, 0x74, 0x65, 0x72, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12,
	0x49, 0x0a, 0x08, 0x47, 0x65, 0x74, 0x53, 0x74, 0x61, 0x74, 0x73, 0x12, 0x1d, 0x2e, 0x70, 0x61,
	0x67, 0x65, 0x63, 0x61, 0x63, 0x68, 0x65, 0x2e, 0x76, 0x31, 0x2e, 0x47, 0x65, 0x74, 0x53, 0x74,
	0x61, 0x74, 0x73, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x1e, 0x2e, 0x70, 0x61, 0x67,
	0x65, 0x63, 0x61, 0x63, 0x68, 0x65, 0x2e, 0x76, 0x31, 0x2e, 0x47, 0x65, 0x74, 0x53, 0x74, 0x61,
	0x74, 0x73, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x42, 0x34, 0x5a, 0x32, 0x67, 0x69,
	0x74, 0x68, 0x75, 0x62, 0x2e, 0x63, 0x6f, 0x6d, 0x2f, 0x72, 0x65, 0x79, 0x6f, 0x75, 0x6e, 0x67,
	0x2f, 0x61, 0x66, 0x73, 0x2f, 0x70, 0x6b, 0x67, 0x2f, 0x70, 0x61, 0x67, 0x65, 0x63, 0x61, 0x63,
	0x68, 0x65, 0x70, 0x62, 0x3b, 0x70, 0x61, 0x67, 0x65, 0x63, 0x61, 0x63, 0x68, 0x65, 0x70, 0x62,
	0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
})

var (
	file_api_pagecache_v1_pagecache_proto_rawDescOnce sync.Once
	file_api_pagecache_v1_pagecache_proto_rawDescData []byte
)

func file_api_pagecache_v1_pagecache_proto_rawDescGZIP() []byte {
	file_api_pagecache_v1_pagecache_proto_rawDescOnce.Do(func() {
		file_api_pagecache_v1_pagecache_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_api_pagecache_v1_pagecache_proto_rawDesc), len(file_api_pagecache_v1_pagecache_proto_rawDesc)))
	})
	return file_api_pagecache_v1_pagecache_proto_rawDescData
}

var file_api_pagecache_v1_pagecache_proto_enumTypes = make([]protoimpl.EnumInfo, 2)
var file_api_pagecache_v1_pagecache_proto_msgTypes = make([]protoimpl.MessageInfo, 15)
var file_api_pagecache_v1_pagecache_proto_goTypes = []any{
	(PutPageStatus)(0),           // 0: pagecache.v1.PutPageStatus
	(GetPageStatus)(0),           // 1: pagecache.v1.GetPageStatus
	(*PutPageChunk)(nil),         // 2: pagecache.v1.PutPageChunk
	(*PutPageHeader)(nil),        // 3: pagecache.v1.PutPageHeader
	(*PutPageResponse)(nil),      // 4: pagecache.v1.PutPageResponse
	(*GetPageRequest)(nil),       // 5: pagecache.v1.GetPageRequest
	(*GetPageResponse)(nil),      // 6: pagecache.v1.GetPageResponse
	(*ReleaseRequest)(nil),       // 7: pagecache.v1.ReleaseRequest
	(*ReleaseResponse)(nil),      // 8: pagecache.v1.ReleaseResponse
	(*BatchGetPageRequest)(nil),  // 9: pagecache.v1.BatchGetPageRequest
	(*BatchGetPageResponse)(nil), // 10: pagecache.v1.BatchGetPageResponse
	(*BatchReleaseRequest)(nil),  // 11: pagecache.v1.BatchReleaseRequest
	(*BatchReleaseResponse)(nil), // 12: pagecache.v1.BatchReleaseResponse
	(*RegisterRequest)(nil),      // 13: pagecache.v1.RegisterRequest
	(*RegisterResponse)(nil),     // 14: pagecache.v1.RegisterResponse
	(*GetStatsRequest)(nil),      // 15: pagecache.v1.GetStatsRequest
	(*GetStatsResponse)(nil),     // 16: pagecache.v1.GetStatsResponse
}
var file_api_pagecache_v1_pagecache_proto_depIdxs = []int32{
	3,  // 0: pagecache.v1.PutPageChunk.header:type_name -> pagecache.v1.PutPageHeader
	0,  // 1: pagecache.v1.PutPageResponse.status:type_name -> pagecache.v1.PutPageStatus
	1,  // 2: pagecache.v1.GetPageResponse.status:type_name -> pagecache.v1.GetPageStatus
	5,  // 3: pagecache.v1.BatchGetPageRequest.pages:type_name -> pagecache.v1.GetPageRequest
	6,  // 4: pagecache.v1.BatchGetPageResponse.pages:type_name -> pagecache.v1.GetPageResponse
	2,  // 5: pagecache.v1.PageCacheService.PutPage:input_type -> pagecache.v1.PutPageChunk
	5,  // 6: pagecache.v1.PageCacheService.GetPage:input_type -> pagecache.v1.GetPageRequest
	7,  // 7: pagecache.v1.PageCacheService.Release:input_type -> pagecache.v1.ReleaseRequest
	9,  // 8: pagecache.v1.PageCacheService.BatchGetPage:input_type -> pagecache.v1.BatchGetPageRequest
	11, // 9: pagecache.v1.PageCacheService.BatchRelease:input_type -> pagecache.v1.BatchReleaseRequest
	13, // 10: pagecache.v1.PageCacheService.Register:input_type -> pagecache.v1.RegisterRequest
	15, // 11: pagecache.v1.PageCacheService.GetStats:input_type -> pagecache.v1.GetStatsRequest
	4,  // 12: pagecache.v1.PageCacheService.PutPage:output_type -> pagecache.v1.PutPageResponse
	6,  // 13: pagecache.v1.PageCacheService.GetPage:output_type -> pagecache.v1.GetPageResponse
	8,  // 14: pagecache.v1.PageCacheService.Release:output_type -> pagecache.v1.ReleaseResponse
	10, // 15: pagecache.v1.PageCacheService.BatchGetPage:output_type -> pagecache.v1.BatchGetPageResponse
	12, // 16: pagecache.v1.PageCacheService.BatchRelease:output_type -> pagecache.v1.BatchReleaseResponse
	14, // 17: pagecache.v1.PageCacheService.Register:output_type -> pagecache.v1.RegisterResponse
	16, // 18: pagecache.v1.PageCacheService.GetStats:output_type -> pagecache.v1.GetStatsResponse
	12, // [12:19] is the sub-list for method output_type
	5,  // [5:12] is the sub-list for method input_type
	5,  // [5:5] is the sub-list for extension type_name
	5,  // [5:5] is the sub-list for extension extendee
	0,  // [0:5] is the sub-list for field type_name
}

func init() { file_api_pagecache_v1_pagecache_proto_init() }
func file_api_pagecache_v1_pagecache_proto_init() {
	if File_api_pagecache_v1_pagecache_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_api_pagecache_v1_pagecache_proto_rawDesc), len(file_api_pagecache_v1_pagecache_proto_rawDesc)),
			NumEnums:      2,
			NumMessages:   15,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_api_pagecache_v1_pagecache_proto_goTypes,
		DependencyIndexes: file_api_pagecache_v1_pagecache_proto_depIdxs,
		EnumInfos:         file_api_pagecache_v1_pagecache_proto_enumTypes,
		MessageInfos:      file_api_pagecache_v1_pagecache_proto_msgTypes,
	}.Build()
	File_api_pagecache_v1_pagecache_proto = out.File
	file_api_pagecache_v1_pagecache_proto_goTypes = nil
	file_api_pagecache_v1_pagecache_proto_depIdxs = nil
}
