// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v4.24.2
// source: api/afsproxy/v1/afsproxy.proto

package afsproxypb

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	AfsProxy_Status_FullMethodName = "/afsproxy.v1.AfsProxy/Status"
)

// AfsProxyClient is the client API for AfsProxy service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type AfsProxyClient interface {
	Status(ctx context.Context, in *StatusRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[StatusResponse], error)
}

type afsProxyClient struct {
	cc grpc.ClientConnInterface
}

func NewAfsProxyClient(cc grpc.ClientConnInterface) AfsProxyClient {
	return &afsProxyClient{cc}
}

func (c *afsProxyClient) Status(ctx context.Context, in *StatusRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[StatusResponse], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &AfsProxy_ServiceDesc.Streams[0], AfsProxy_Status_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[StatusRequest, StatusResponse]{ClientStream: stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type AfsProxy_StatusClient = grpc.ServerStreamingClient[StatusResponse]

// AfsProxyServer is the server API for AfsProxy service.
// All implementations must embed UnimplementedAfsProxyServer
// for forward compatibility.
type AfsProxyServer interface {
	Status(*StatusRequest, grpc.ServerStreamingServer[StatusResponse]) error
	mustEmbedUnimplementedAfsProxyServer()
}

// UnimplementedAfsProxyServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedAfsProxyServer struct{}

func (UnimplementedAfsProxyServer) Status(*StatusRequest, grpc.ServerStreamingServer[StatusResponse]) error {
	return status.Errorf(codes.Unimplemented, "method Status not implemented")
}
func (UnimplementedAfsProxyServer) mustEmbedUnimplementedAfsProxyServer() {}
func (UnimplementedAfsProxyServer) testEmbeddedByValue()                  {}

// UnsafeAfsProxyServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to AfsProxyServer will
// result in compilation errors.
type UnsafeAfsProxyServer interface {
	mustEmbedUnimplementedAfsProxyServer()
}

func RegisterAfsProxyServer(s grpc.ServiceRegistrar, srv AfsProxyServer) {
	// If the following call pancis, it indicates UnimplementedAfsProxyServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&AfsProxy_ServiceDesc, srv)
}

func _AfsProxy_Status_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(StatusRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(AfsProxyServer).Status(m, &grpc.GenericServerStream[StatusRequest, StatusResponse]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type AfsProxy_StatusServer = grpc.ServerStreamingServer[StatusResponse]

// AfsProxy_ServiceDesc is the grpc.ServiceDesc for AfsProxy service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var AfsProxy_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "afsproxy.v1.AfsProxy",
	HandlerType: (*AfsProxyServer)(nil),
	Methods:     []grpc.MethodDesc{},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "Status",
			Handler:       _AfsProxy_Status_Handler,
			ServerStreams: true,
		},
	},
	Metadata: "api/afsproxy/v1/afsproxy.proto",
}
