// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.1
// 	protoc        v5.28.3
// source: api/afslet/v1/afslet.proto

package afsletpb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type FileType int32

const (
	FileType_FILE_TYPE_DIR     FileType = 0
	FileType_FILE_TYPE_FILE    FileType = 1
	FileType_FILE_TYPE_SYMLINK FileType = 2
)

// Enum value maps for FileType.
var (
	FileType_name = map[int32]string{
		0: "FILE_TYPE_DIR",
		1: "FILE_TYPE_FILE",
		2: "FILE_TYPE_SYMLINK",
	}
	FileType_value = map[string]int32{
		"FILE_TYPE_DIR":     0,
		"FILE_TYPE_FILE":    1,
		"FILE_TYPE_SYMLINK": 2,
	}
)

func (x FileType) Enum() *FileType {
	p := new(FileType)
	*p = x
	return p
}

func (x FileType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (FileType) Descriptor() protoreflect.EnumDescriptor {
	return file_api_afslet_v1_afslet_proto_enumTypes[0].Descriptor()
}

func (FileType) Type() protoreflect.EnumType {
	return &file_api_afslet_v1_afslet_proto_enumTypes[0]
}

func (x FileType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use FileType.Descriptor instead.
func (FileType) EnumDescriptor() ([]byte, []int) {
	return file_api_afslet_v1_afslet_proto_rawDescGZIP(), []int{0}
}

type ExecuteRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to Payload:
	//
	//	*ExecuteRequest_Start
	//	*ExecuteRequest_FileBegin
	//	*ExecuteRequest_FileChunk
	//	*ExecuteRequest_FileEnd
	Payload       isExecuteRequest_Payload `protobuf_oneof:"payload"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ExecuteRequest) Reset() {
	*x = ExecuteRequest{}
	mi := &file_api_afslet_v1_afslet_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ExecuteRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ExecuteRequest) ProtoMessage() {}

func (x *ExecuteRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_afslet_v1_afslet_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ExecuteRequest.ProtoReflect.Descriptor instead.
func (*ExecuteRequest) Descriptor() ([]byte, []int) {
	return file_api_afslet_v1_afslet_proto_rawDescGZIP(), []int{0}
}

func (x *ExecuteRequest) GetPayload() isExecuteRequest_Payload {
	if x != nil {
		return x.Payload
	}
	return nil
}

func (x *ExecuteRequest) GetStart() *StartRequest {
	if x != nil {
		if x, ok := x.Payload.(*ExecuteRequest_Start); ok {
			return x.Start
		}
	}
	return nil
}

func (x *ExecuteRequest) GetFileBegin() *FileEntryBegin {
	if x != nil {
		if x, ok := x.Payload.(*ExecuteRequest_FileBegin); ok {
			return x.FileBegin
		}
	}
	return nil
}

func (x *ExecuteRequest) GetFileChunk() *FileChunk {
	if x != nil {
		if x, ok := x.Payload.(*ExecuteRequest_FileChunk); ok {
			return x.FileChunk
		}
	}
	return nil
}

func (x *ExecuteRequest) GetFileEnd() *FileEntryEnd {
	if x != nil {
		if x, ok := x.Payload.(*ExecuteRequest_FileEnd); ok {
			return x.FileEnd
		}
	}
	return nil
}

type isExecuteRequest_Payload interface {
	isExecuteRequest_Payload()
}

type ExecuteRequest_Start struct {
	Start *StartRequest `protobuf:"bytes,1,opt,name=start,proto3,oneof"`
}

type ExecuteRequest_FileBegin struct {
	FileBegin *FileEntryBegin `protobuf:"bytes,2,opt,name=file_begin,json=fileBegin,proto3,oneof"`
}

type ExecuteRequest_FileChunk struct {
	FileChunk *FileChunk `protobuf:"bytes,3,opt,name=file_chunk,json=fileChunk,proto3,oneof"`
}

type ExecuteRequest_FileEnd struct {
	FileEnd *FileEntryEnd `protobuf:"bytes,4,opt,name=file_end,json=fileEnd,proto3,oneof"`
}

func (*ExecuteRequest_Start) isExecuteRequest_Payload() {}

func (*ExecuteRequest_FileBegin) isExecuteRequest_Payload() {}

func (*ExecuteRequest_FileChunk) isExecuteRequest_Payload() {}

func (*ExecuteRequest_FileEnd) isExecuteRequest_Payload() {}

type StartRequest struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	Image           string                 `protobuf:"bytes,1,opt,name=image,proto3" json:"image,omitempty"`
	Tag             string                 `protobuf:"bytes,2,opt,name=tag,proto3" json:"tag,omitempty"`
	Command         []string               `protobuf:"bytes,3,rep,name=command,proto3" json:"command,omitempty"`
	CpuCores        int64                  `protobuf:"varint,4,opt,name=cpu_cores,json=cpuCores,proto3" json:"cpu_cores,omitempty"`
	MemoryMb        int64                  `protobuf:"varint,5,opt,name=memory_mb,json=memoryMb,proto3" json:"memory_mb,omitempty"`
	TimeoutMs       int64                  `protobuf:"varint,6,opt,name=timeout_ms,json=timeoutMs,proto3" json:"timeout_ms,omitempty"`
	DiscoveryAddr   string                 `protobuf:"bytes,7,opt,name=discovery_addr,json=discoveryAddr,proto3" json:"discovery_addr,omitempty"`
	ForcePull       bool                   `protobuf:"varint,8,opt,name=force_pull,json=forcePull,proto3" json:"force_pull,omitempty"`
	NodeId          string                 `protobuf:"bytes,9,opt,name=node_id,json=nodeId,proto3" json:"node_id,omitempty"`
	PlatformOs      string                 `protobuf:"bytes,10,opt,name=platform_os,json=platformOs,proto3" json:"platform_os,omitempty"`
	PlatformArch    string                 `protobuf:"bytes,11,opt,name=platform_arch,json=platformArch,proto3" json:"platform_arch,omitempty"`
	PlatformVariant string                 `protobuf:"bytes,12,opt,name=platform_variant,json=platformVariant,proto3" json:"platform_variant,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *StartRequest) Reset() {
	*x = StartRequest{}
	mi := &file_api_afslet_v1_afslet_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StartRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StartRequest) ProtoMessage() {}

func (x *StartRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_afslet_v1_afslet_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StartRequest.ProtoReflect.Descriptor instead.
func (*StartRequest) Descriptor() ([]byte, []int) {
	return file_api_afslet_v1_afslet_proto_rawDescGZIP(), []int{1}
}

func (x *StartRequest) GetImage() string {
	if x != nil {
		return x.Image
	}
	return ""
}

func (x *StartRequest) GetTag() string {
	if x != nil {
		return x.Tag
	}
	return ""
}

func (x *StartRequest) GetCommand() []string {
	if x != nil {
		return x.Command
	}
	return nil
}

func (x *StartRequest) GetCpuCores() int64 {
	if x != nil {
		return x.CpuCores
	}
	return 0
}

func (x *StartRequest) GetMemoryMb() int64 {
	if x != nil {
		return x.MemoryMb
	}
	return 0
}

func (x *StartRequest) GetTimeoutMs() int64 {
	if x != nil {
		return x.TimeoutMs
	}
	return 0
}

func (x *StartRequest) GetDiscoveryAddr() string {
	if x != nil {
		return x.DiscoveryAddr
	}
	return ""
}

func (x *StartRequest) GetForcePull() bool {
	if x != nil {
		return x.ForcePull
	}
	return false
}

func (x *StartRequest) GetNodeId() string {
	if x != nil {
		return x.NodeId
	}
	return ""
}

func (x *StartRequest) GetPlatformOs() string {
	if x != nil {
		return x.PlatformOs
	}
	return ""
}

func (x *StartRequest) GetPlatformArch() string {
	if x != nil {
		return x.PlatformArch
	}
	return ""
}

func (x *StartRequest) GetPlatformVariant() string {
	if x != nil {
		return x.PlatformVariant
	}
	return ""
}

type FileEntryBegin struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Path          string                 `protobuf:"bytes,1,opt,name=path,proto3" json:"path,omitempty"`
	Type          FileType               `protobuf:"varint,2,opt,name=type,proto3,enum=afsletpb.FileType" json:"type,omitempty"`
	Mode          uint32                 `protobuf:"varint,3,opt,name=mode,proto3" json:"mode,omitempty"`
	Uid           uint32                 `protobuf:"varint,4,opt,name=uid,proto3" json:"uid,omitempty"`
	Gid           uint32                 `protobuf:"varint,5,opt,name=gid,proto3" json:"gid,omitempty"`
	MtimeUnix     int64                  `protobuf:"varint,6,opt,name=mtime_unix,json=mtimeUnix,proto3" json:"mtime_unix,omitempty"`
	SymlinkTarget string                 `protobuf:"bytes,7,opt,name=symlink_target,json=symlinkTarget,proto3" json:"symlink_target,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FileEntryBegin) Reset() {
	*x = FileEntryBegin{}
	mi := &file_api_afslet_v1_afslet_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FileEntryBegin) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FileEntryBegin) ProtoMessage() {}

func (x *FileEntryBegin) ProtoReflect() protoreflect.Message {
	mi := &file_api_afslet_v1_afslet_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FileEntryBegin.ProtoReflect.Descriptor instead.
func (*FileEntryBegin) Descriptor() ([]byte, []int) {
	return file_api_afslet_v1_afslet_proto_rawDescGZIP(), []int{2}
}

func (x *FileEntryBegin) GetPath() string {
	if x != nil {
		return x.Path
	}
	return ""
}

func (x *FileEntryBegin) GetType() FileType {
	if x != nil {
		return x.Type
	}
	return FileType_FILE_TYPE_DIR
}

func (x *FileEntryBegin) GetMode() uint32 {
	if x != nil {
		return x.Mode
	}
	return 0
}

func (x *FileEntryBegin) GetUid() uint32 {
	if x != nil {
		return x.Uid
	}
	return 0
}

func (x *FileEntryBegin) GetGid() uint32 {
	if x != nil {
		return x.Gid
	}
	return 0
}

func (x *FileEntryBegin) GetMtimeUnix() int64 {
	if x != nil {
		return x.MtimeUnix
	}
	return 0
}

func (x *FileEntryBegin) GetSymlinkTarget() string {
	if x != nil {
		return x.SymlinkTarget
	}
	return ""
}

type FileChunk struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Data          []byte                 `protobuf:"bytes,1,opt,name=data,proto3" json:"data,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FileChunk) Reset() {
	*x = FileChunk{}
	mi := &file_api_afslet_v1_afslet_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FileChunk) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FileChunk) ProtoMessage() {}

func (x *FileChunk) ProtoReflect() protoreflect.Message {
	mi := &file_api_afslet_v1_afslet_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FileChunk.ProtoReflect.Descriptor instead.
func (*FileChunk) Descriptor() ([]byte, []int) {
	return file_api_afslet_v1_afslet_proto_rawDescGZIP(), []int{3}
}

func (x *FileChunk) GetData() []byte {
	if x != nil {
		return x.Data
	}
	return nil
}

type FileEntryEnd struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FileEntryEnd) Reset() {
	*x = FileEntryEnd{}
	mi := &file_api_afslet_v1_afslet_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FileEntryEnd) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FileEntryEnd) ProtoMessage() {}

func (x *FileEntryEnd) ProtoReflect() protoreflect.Message {
	mi := &file_api_afslet_v1_afslet_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FileEntryEnd.ProtoReflect.Descriptor instead.
func (*FileEntryEnd) Descriptor() ([]byte, []int) {
	return file_api_afslet_v1_afslet_proto_rawDescGZIP(), []int{4}
}

type ExecuteResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to Payload:
	//
	//	*ExecuteResponse_Log
	//	*ExecuteResponse_Result
	//	*ExecuteResponse_TarHeader
	//	*ExecuteResponse_TarChunk
	//	*ExecuteResponse_Done
	Payload       isExecuteResponse_Payload `protobuf_oneof:"payload"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ExecuteResponse) Reset() {
	*x = ExecuteResponse{}
	mi := &file_api_afslet_v1_afslet_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ExecuteResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ExecuteResponse) ProtoMessage() {}

func (x *ExecuteResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_afslet_v1_afslet_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ExecuteResponse.ProtoReflect.Descriptor instead.
func (*ExecuteResponse) Descriptor() ([]byte, []int) {
	return file_api_afslet_v1_afslet_proto_rawDescGZIP(), []int{5}
}

func (x *ExecuteResponse) GetPayload() isExecuteResponse_Payload {
	if x != nil {
		return x.Payload
	}
	return nil
}

func (x *ExecuteResponse) GetLog() *LogMessage {
	if x != nil {
		if x, ok := x.Payload.(*ExecuteResponse_Log); ok {
			return x.Log
		}
	}
	return nil
}

func (x *ExecuteResponse) GetResult() *Result {
	if x != nil {
		if x, ok := x.Payload.(*ExecuteResponse_Result); ok {
			return x.Result
		}
	}
	return nil
}

func (x *ExecuteResponse) GetTarHeader() *TarHeader {
	if x != nil {
		if x, ok := x.Payload.(*ExecuteResponse_TarHeader); ok {
			return x.TarHeader
		}
	}
	return nil
}

func (x *ExecuteResponse) GetTarChunk() *TarChunk {
	if x != nil {
		if x, ok := x.Payload.(*ExecuteResponse_TarChunk); ok {
			return x.TarChunk
		}
	}
	return nil
}

func (x *ExecuteResponse) GetDone() *Done {
	if x != nil {
		if x, ok := x.Payload.(*ExecuteResponse_Done); ok {
			return x.Done
		}
	}
	return nil
}

type isExecuteResponse_Payload interface {
	isExecuteResponse_Payload()
}

type ExecuteResponse_Log struct {
	Log *LogMessage `protobuf:"bytes,1,opt,name=log,proto3,oneof"`
}

type ExecuteResponse_Result struct {
	Result *Result `protobuf:"bytes,2,opt,name=result,proto3,oneof"`
}

type ExecuteResponse_TarHeader struct {
	TarHeader *TarHeader `protobuf:"bytes,3,opt,name=tar_header,json=tarHeader,proto3,oneof"`
}

type ExecuteResponse_TarChunk struct {
	TarChunk *TarChunk `protobuf:"bytes,4,opt,name=tar_chunk,json=tarChunk,proto3,oneof"`
}

type ExecuteResponse_Done struct {
	Done *Done `protobuf:"bytes,5,opt,name=done,proto3,oneof"`
}

func (*ExecuteResponse_Log) isExecuteResponse_Payload() {}

func (*ExecuteResponse_Result) isExecuteResponse_Payload() {}

func (*ExecuteResponse_TarHeader) isExecuteResponse_Payload() {}

func (*ExecuteResponse_TarChunk) isExecuteResponse_Payload() {}

func (*ExecuteResponse_Done) isExecuteResponse_Payload() {}

type LogMessage struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Source        string                 `protobuf:"bytes,1,opt,name=source,proto3" json:"source,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LogMessage) Reset() {
	*x = LogMessage{}
	mi := &file_api_afslet_v1_afslet_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LogMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LogMessage) ProtoMessage() {}

func (x *LogMessage) ProtoReflect() protoreflect.Message {
	mi := &file_api_afslet_v1_afslet_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LogMessage.ProtoReflect.Descriptor instead.
func (*LogMessage) Descriptor() ([]byte, []int) {
	return file_api_afslet_v1_afslet_proto_rawDescGZIP(), []int{6}
}

func (x *LogMessage) GetSource() string {
	if x != nil {
		return x.Source
	}
	return ""
}

func (x *LogMessage) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

type Result struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	ExitCode      int32                  `protobuf:"varint,2,opt,name=exit_code,json=exitCode,proto3" json:"exit_code,omitempty"`
	Error         string                 `protobuf:"bytes,3,opt,name=error,proto3" json:"error,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Result) Reset() {
	*x = Result{}
	mi := &file_api_afslet_v1_afslet_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Result) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Result) ProtoMessage() {}

func (x *Result) ProtoReflect() protoreflect.Message {
	mi := &file_api_afslet_v1_afslet_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Result.ProtoReflect.Descriptor instead.
func (*Result) Descriptor() ([]byte, []int) {
	return file_api_afslet_v1_afslet_proto_rawDescGZIP(), []int{7}
}

func (x *Result) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *Result) GetExitCode() int32 {
	if x != nil {
		return x.ExitCode
	}
	return 0
}

func (x *Result) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

type TarHeader struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TarHeader) Reset() {
	*x = TarHeader{}
	mi := &file_api_afslet_v1_afslet_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TarHeader) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TarHeader) ProtoMessage() {}

func (x *TarHeader) ProtoReflect() protoreflect.Message {
	mi := &file_api_afslet_v1_afslet_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TarHeader.ProtoReflect.Descriptor instead.
func (*TarHeader) Descriptor() ([]byte, []int) {
	return file_api_afslet_v1_afslet_proto_rawDescGZIP(), []int{8}
}

func (x *TarHeader) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

type TarChunk struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Data          []byte                 `protobuf:"bytes,1,opt,name=data,proto3" json:"data,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TarChunk) Reset() {
	*x = TarChunk{}
	mi := &file_api_afslet_v1_afslet_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TarChunk) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TarChunk) ProtoMessage() {}

func (x *TarChunk) ProtoReflect() protoreflect.Message {
	mi := &file_api_afslet_v1_afslet_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TarChunk.ProtoReflect.Descriptor instead.
func (*TarChunk) Descriptor() ([]byte, []int) {
	return file_api_afslet_v1_afslet_proto_rawDescGZIP(), []int{9}
}

func (x *TarChunk) GetData() []byte {
	if x != nil {
		return x.Data
	}
	return nil
}

type Done struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Done) Reset() {
	*x = Done{}
	mi := &file_api_afslet_v1_afslet_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Done) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Done) ProtoMessage() {}

func (x *Done) ProtoReflect() protoreflect.Message {
	mi := &file_api_afslet_v1_afslet_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Done.ProtoReflect.Descriptor instead.
func (*Done) Descriptor() ([]byte, []int) {
	return file_api_afslet_v1_afslet_proto_rawDescGZIP(), []int{10}
}

type GetRuntimeStatusRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetRuntimeStatusRequest) Reset() {
	*x = GetRuntimeStatusRequest{}
	mi := &file_api_afslet_v1_afslet_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetRuntimeStatusRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetRuntimeStatusRequest) ProtoMessage() {}

func (x *GetRuntimeStatusRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_afslet_v1_afslet_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetRuntimeStatusRequest.ProtoReflect.Descriptor instead.
func (*GetRuntimeStatusRequest) Descriptor() ([]byte, []int) {
	return file_api_afslet_v1_afslet_proto_rawDescGZIP(), []int{11}
}

type GetRuntimeStatusResponse struct {
	state             protoimpl.MessageState `protogen:"open.v1"`
	RunningContainers int64                  `protobuf:"varint,1,opt,name=running_containers,json=runningContainers,proto3" json:"running_containers,omitempty"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *GetRuntimeStatusResponse) Reset() {
	*x = GetRuntimeStatusResponse{}
	mi := &file_api_afslet_v1_afslet_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetRuntimeStatusResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetRuntimeStatusResponse) ProtoMessage() {}

func (x *GetRuntimeStatusResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_afslet_v1_afslet_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetRuntimeStatusResponse.ProtoReflect.Descriptor instead.
func (*GetRuntimeStatusResponse) Descriptor() ([]byte, []int) {
	return file_api_afslet_v1_afslet_proto_rawDescGZIP(), []int{12}
}

func (x *GetRuntimeStatusResponse) GetRunningContainers() int64 {
	if x != nil {
		return x.RunningContainers
	}
	return 0
}

var File_api_afslet_v1_afslet_proto protoreflect.FileDescriptor

var file_api_afslet_v1_afslet_proto_rawDesc = []byte{
	0x0a, 0x1a, 0x61, 0x70, 0x69, 0x2f, 0x61, 0x66, 0x73, 0x6c, 0x65, 0x74, 0x2f, 0x76, 0x31, 0x2f,
	0x61, 0x66, 0x73, 0x6c, 0x65, 0x74, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x08, 0x61, 0x66,
	0x73, 0x6c, 0x65, 0x74, 0x70, 0x62, 0x22, 0xf1, 0x01, 0x0a, 0x0e, 0x45, 0x78, 0x65, 0x63, 0x75,
	0x74, 0x65, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x2e, 0x0a, 0x05, 0x73, 0x74, 0x61,
	0x72, 0x74, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x16, 0x2e, 0x61, 0x66, 0x73, 0x6c, 0x65,
	0x74, 0x70, 0x62, 0x2e, 0x53, 0x74, 0x61, 0x72, 0x74, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74,
	0x48, 0x00, 0x52, 0x05, 0x73, 0x74, 0x61, 0x72, 0x74, 0x12, 0x39, 0x0a, 0x0a, 0x66, 0x69, 0x6c,
	0x65, 0x5f, 0x62, 0x65, 0x67, 0x69, 0x6e, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x18, 0x2e,
	0x61, 0x66, 0x73, 0x6c, 0x65, 0x74, 0x70, 0x62, 0x2e, 0x46, 0x69, 0x6c, 0x65, 0x45, 0x6e, 0x74,
	0x72, 0x79, 0x42, 0x65, 0x67, 0x69, 0x6e, 0x48, 0x00, 0x52, 0x09, 0x66, 0x69, 0x6c, 0x65, 0x42,
	0x65, 0x67, 0x69, 0x6e, 0x12, 0x34, 0x0a, 0x0a, 0x66, 0x69, 0x6c, 0x65, 0x5f, 0x63, 0x68, 0x75,
	0x6e, 0x6b, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x13, 0x2e, 0x61, 0x66, 0x73, 0x6c, 0x65,
	0x74, 0x70, 0x62, 0x2e, 0x46, 0x69, 0x6c, 0x65, 0x43, 0x68, 0x75, 0x6e, 0x6b, 0x48, 0x00, 0x52,
	0x09, 0x66, 0x69, 0x6c, 0x65, 0x43, 0x68, 0x75, 0x6e, 0x6b, 0x12, 0x33, 0x0a, 0x08, 0x66, 0x69,
	0x6c, 0x65, 0x5f, 0x65, 0x6e, 0x64, 0x18, 0x04, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x16, 0x2e, 0x61,
	0x66, 0x73, 0x6c, 0x65, 0x74, 0x70, 0x62, 0x2e, 0x46, 0x69, 0x6c, 0x65, 0x45, 0x6e, 0x74, 0x72,
	0x79, 0x45, 0x6e, 0x64, 0x48, 0x00, 0x52, 0x07, 0x66, 0x69, 0x6c, 0x65, 0x45, 0x6e, 0x64, 0x42,
	0x09, 0x0a, 0x07, 0x70, 0x61, 0x79, 0x6c, 0x6f, 0x61, 0x64, 0x22, 0xf9, 0x02, 0x0a, 0x0c, 0x53,
	0x74, 0x61, 0x72, 0x74, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x14, 0x0a, 0x05, 0x69,
	0x6d, 0x61, 0x67, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x69, 0x6d, 0x61, 0x67,
	0x65, 0x12, 0x10, 0x0a, 0x03, 0x74, 0x61, 0x67, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x03,
	0x74, 0x61, 0x67, 0x12, 0x18, 0x0a, 0x07, 0x63, 0x6f, 0x6d, 0x6d, 0x61, 0x6e, 0x64, 0x18, 0x03,
	0x20, 0x03, 0x28, 0x09, 0x52, 0x07, 0x63, 0x6f, 0x6d, 0x6d, 0x61, 0x6e, 0x64, 0x12, 0x1b, 0x0a,
	0x09, 0x63, 0x70, 0x75, 0x5f, 0x63, 0x6f, 0x72, 0x65, 0x73, 0x18, 0x04, 0x20, 0x01, 0x28, 0x03,
	0x52, 0x08, 0x63, 0x70, 0x75, 0x43, 0x6f, 0x72, 0x65, 0x73, 0x12, 0x1b, 0x0a, 0x09, 0x6d, 0x65,
	0x6d, 0x6f, 0x72, 0x79, 0x5f, 0x6d, 0x62, 0x18, 0x05, 0x20, 0x01, 0x28, 0x03, 0x52, 0x08, 0x6d,
	0x65, 0x6d, 0x6f, 0x72, 0x79, 0x4d, 0x62, 0x12, 0x1d, 0x0a, 0x0a, 0x74, 0x69, 0x6d, 0x65, 0x6f,
	0x75, 0x74, 0x5f, 0x6d, 0x73, 0x18, 0x06, 0x20, 0x01, 0x28, 0x03, 0x52, 0x09, 0x74, 0x69, 0x6d,
	0x65, 0x6f, 0x75, 0x74, 0x4d, 0x73, 0x12, 0x25, 0x0a, 0x0e, 0x64, 0x69, 0x73, 0x63, 0x6f, 0x76,
	0x65, 0x72, 0x79, 0x5f, 0x61, 0x64, 0x64, 0x72, 0x18, 0x07, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0d,
	0x64, 0x69, 0x73, 0x63, 0x6f, 0x76, 0x65, 0x72, 0x79, 0x41, 0x64, 0x64, 0x72, 0x12, 0x1d, 0x0a,
	0x0a, 0x66, 0x6f, 0x72, 0x63, 0x65, 0x5f, 0x70, 0x75, 0x6c, 0x6c, 0x18, 0x08, 0x20, 0x01, 0x28,
	0x08, 0x52, 0x09, 0x66, 0x6f, 0x72, 0x63, 0x65, 0x50, 0x75, 0x6c, 0x6c, 0x12, 0x17, 0x0a, 0x07,
	0x6e, 0x6f, 0x64, 0x65, 0x5f, 0x69, 0x64, 0x18, 0x09, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x6e,
	0x6f, 0x64, 0x65, 0x49, 0x64, 0x12, 0x1f, 0x0a, 0x0b, 0x70, 0x6c, 0x61, 0x74, 0x66, 0x6f, 0x72,
	0x6d, 0x5f, 0x6f, 0x73, 0x18, 0x0a, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0a, 0x70, 0x6c, 0x61, 0x74,
	0x66, 0x6f, 0x72, 0x6d, 0x4f, 0x73, 0x12, 0x23, 0x0a, 0x0d, 0x70, 0x6c, 0x61, 0x74, 0x66, 0x6f,
	0x72, 0x6d, 0x5f, 0x61, 0x72, 0x63, 0x68, 0x18, 0x0b, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0c, 0x70,
	0x6c, 0x61, 0x74, 0x66, 0x6f, 0x72, 0x6d, 0x41, 0x72, 0x63, 0x68, 0x12, 0x29, 0x0a, 0x10, 0x70,
	0x6c, 0x61, 0x74, 0x66, 0x6f, 0x72, 0x6d, 0x5f, 0x76, 0x61, 0x72, 0x69, 0x61, 0x6e, 0x74, 0x18,
	0x0c, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0f, 0x70, 0x6c, 0x61, 0x74, 0x66, 0x6f, 0x72, 0x6d, 0x56,
	0x61, 0x72, 0x69, 0x61, 0x6e, 0x74, 0x22, 0xca, 0x01, 0x0a, 0x0e, 0x46, 0x69, 0x6c, 0x65, 0x45,
	0x6e, 0x74, 0x72, 0x79, 0x42, 0x65, 0x67, 0x69, 0x6e, 0x12, 0x12, 0x0a, 0x04, 0x70, 0x61, 0x74,
	0x68, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x70, 0x61, 0x74, 0x68, 0x12, 0x26, 0x0a,
	0x04, 0x74, 0x79, 0x70, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x12, 0x2e, 0x61, 0x66,
	0x73, 0x6c, 0x65, 0x74, 0x70, 0x62, 0x2e, 0x46, 0x69, 0x6c, 0x65, 0x54, 0x79, 0x70, 0x65, 0x52,
	0x04, 0x74, 0x79, 0x70, 0x65, 0x12, 0x12, 0x0a, 0x04, 0x6d, 0x6f, 0x64, 0x65, 0x18, 0x03, 0x20,
	0x01, 0x28, 0x0d, 0x52, 0x04, 0x6d, 0x6f, 0x64, 0x65, 0x12, 0x10, 0x0a, 0x03, 0x75, 0x69, 0x64,
	0x18, 0x04, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x03, 0x75, 0x69, 0x64, 0x12, 0x10, 0x0a, 0x03, 0x67,
	0x69, 0x64, 0x18, 0x05, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x03, 0x67, 0x69, 0x64, 0x12, 0x1d, 0x0a,
	0x0a, 0x6d, 0x74, 0x69, 0x6d, 0x65, 0x5f, 0x75, 0x6e, 0x69, 0x78, 0x18, 0x06, 0x20, 0x01, 0x28,
	0x03, 0x52, 0x09, 0x6d, 0x74, 0x69, 0x6d, 0x65, 0x55, 0x6e, 0x69, 0x78, 0x12, 0x25, 0x0a, 0x0e,
	0x73, 0x79, 0x6d, 0x6c, 0x69, 0x6e, 0x6b, 0x5f, 0x74, 0x61, 0x72, 0x67, 0x65, 0x74, 0x18, 0x07,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x0d, 0x73, 0x79, 0x6d, 0x6c, 0x69, 0x6e, 0x6b, 0x54, 0x61, 0x72,
	0x67, 0x65, 0x74, 0x22, 0x1f, 0x0a, 0x09, 0x46, 0x69, 0x6c, 0x65, 0x43, 0x68, 0x75, 0x6e, 0x6b,
	0x12, 0x12, 0x0a, 0x04, 0x64, 0x61, 0x74, 0x61, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x04,
	0x64, 0x61, 0x74, 0x61, 0x22, 0x0e, 0x0a, 0x0c, 0x46, 0x69, 0x6c, 0x65, 0x45, 0x6e, 0x74, 0x72,
	0x79, 0x45, 0x6e, 0x64, 0x22, 0x81, 0x02, 0x0a, 0x0f, 0x45, 0x78, 0x65, 0x63, 0x75, 0x74, 0x65,
	0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x28, 0x0a, 0x03, 0x6c, 0x6f, 0x67, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x14, 0x2e, 0x61, 0x66, 0x73, 0x6c, 0x65, 0x74, 0x70, 0x62,
	0x2e, 0x4c, 0x6f, 0x67, 0x4d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x48, 0x00, 0x52, 0x03, 0x6c,
	0x6f, 0x67, 0x12, 0x2a, 0x0a, 0x06, 0x72, 0x65, 0x73, 0x75, 0x6c, 0x74, 0x18, 0x02, 0x20, 0x01,
	0x28, 0x0b, 0x32, 0x10, 0x2e, 0x61, 0x66, 0x73, 0x6c, 0x65, 0x74, 0x70, 0x62, 0x2e, 0x52, 0x65,
	0x73, 0x75, 0x6c, 0x74, 0x48, 0x00, 0x52, 0x06, 0x72, 0x65, 0x73, 0x75, 0x6c, 0x74, 0x12, 0x34,
	0x0a, 0x0a, 0x74, 0x61, 0x72, 0x5f, 0x68, 0x65, 0x61, 0x64, 0x65, 0x72, 0x18, 0x03, 0x20, 0x01,
	0x28, 0x0b, 0x32, 0x13, 0x2e, 0x61, 0x66, 0x73, 0x6c, 0x65, 0x74, 0x70, 0x62, 0x2e, 0x54, 0x61,
	0x72, 0x48, 0x65, 0x61, 0x64, 0x65, 0x72, 0x48, 0x00, 0x52, 0x09, 0x74, 0x61, 0x72, 0x48, 0x65,
	0x61, 0x64, 0x65, 0x72, 0x12, 0x31, 0x0a, 0x09, 0x74, 0x61, 0x72, 0x5f, 0x63, 0x68, 0x75, 0x6e,
	0x6b, 0x18, 0x04, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x12, 0x2e, 0x61, 0x66, 0x73, 0x6c, 0x65, 0x74,
	0x70, 0x62, 0x2e, 0x54, 0x61, 0x72, 0x43, 0x68, 0x75, 0x6e, 0x6b, 0x48, 0x00, 0x52, 0x08, 0x74,
	0x61, 0x72, 0x43, 0x68, 0x75, 0x6e, 0x6b, 0x12, 0x24, 0x0a, 0x04, 0x64, 0x6f, 0x6e, 0x65, 0x18,
	0x05, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x0e, 0x2e, 0x61, 0x66, 0x73, 0x6c, 0x65, 0x74, 0x70, 0x62,
	0x2e, 0x44, 0x6f, 0x6e, 0x65, 0x48, 0x00, 0x52, 0x04, 0x64, 0x6f, 0x6e, 0x65, 0x42, 0x09, 0x0a,
	0x07, 0x70, 0x61, 0x79, 0x6c, 0x6f, 0x61, 0x64, 0x22, 0x3e, 0x0a, 0x0a, 0x4c, 0x6f, 0x67, 0x4d,
	0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x12, 0x16, 0x0a, 0x06, 0x73, 0x6f, 0x75, 0x72, 0x63, 0x65,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x73, 0x6f, 0x75, 0x72, 0x63, 0x65, 0x12, 0x18,
	0x0a, 0x07, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x07, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x22, 0x55, 0x0a, 0x06, 0x52, 0x65, 0x73, 0x75,
	0x6c, 0x74, 0x12, 0x18, 0x0a, 0x07, 0x73, 0x75, 0x63, 0x63, 0x65, 0x73, 0x73, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x08, 0x52, 0x07, 0x73, 0x75, 0x63, 0x63, 0x65, 0x73, 0x73, 0x12, 0x1b, 0x0a, 0x09,
	0x65, 0x78, 0x69, 0x74, 0x5f, 0x63, 0x6f, 0x64, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x05, 0x52,
	0x08, 0x65, 0x78, 0x69, 0x74, 0x43, 0x6f, 0x64, 0x65, 0x12, 0x14, 0x0a, 0x05, 0x65, 0x72, 0x72,
	0x6f, 0x72, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x65, 0x72, 0x72, 0x6f, 0x72, 0x22,
	0x1f, 0x0a, 0x09, 0x54, 0x61, 0x72, 0x48, 0x65, 0x61, 0x64, 0x65, 0x72, 0x12, 0x12, 0x0a, 0x04,
	0x6e, 0x61, 0x6d, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x6e, 0x61, 0x6d, 0x65,
	0x22, 0x1e, 0x0a, 0x08, 0x54, 0x61, 0x72, 0x43, 0x68, 0x75, 0x6e, 0x6b, 0x12, 0x12, 0x0a, 0x04,
	0x64, 0x61, 0x74, 0x61, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x04, 0x64, 0x61, 0x74, 0x61,
	0x22, 0x06, 0x0a, 0x04, 0x44, 0x6f, 0x6e, 0x65, 0x22, 0x19, 0x0a, 0x17, 0x47, 0x65, 0x74, 0x52,
	0x75, 0x6e, 0x74, 0x69, 0x6d, 0x65, 0x53, 0x74, 0x61, 0x74, 0x75, 0x73, 0x52, 0x65, 0x71, 0x75,
	0x65, 0x73, 0x74, 0x22, 0x49, 0x0a, 0x18, 0x47, 0x65, 0x74, 0x52, 0x75, 0x6e, 0x74, 0x69, 0x6d,
	0x65, 0x53, 0x74, 0x61, 0x74, 0x75, 0x73, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12,
	0x2d, 0x0a, 0x12, 0x72, 0x75, 0x6e, 0x6e, 0x69, 0x6e, 0x67, 0x5f, 0x63, 0x6f, 0x6e, 0x74, 0x61,
	0x69, 0x6e, 0x65, 0x72, 0x73, 0x18, 0x01, 0x20, 0x01, 0x28, 0x03, 0x52, 0x11, 0x72, 0x75, 0x6e,
	0x6e, 0x69, 0x6e, 0x67, 0x43, 0x6f, 0x6e, 0x74, 0x61, 0x69, 0x6e, 0x65, 0x72, 0x73, 0x2a, 0x48,
	0x0a, 0x08, 0x46, 0x69, 0x6c, 0x65, 0x54, 0x79, 0x70, 0x65, 0x12, 0x11, 0x0a, 0x0d, 0x46, 0x49,
	0x4c, 0x45, 0x5f, 0x54, 0x59, 0x50, 0x45, 0x5f, 0x44, 0x49, 0x52, 0x10, 0x00, 0x12, 0x12, 0x0a,
	0x0e, 0x46, 0x49, 0x4c, 0x45, 0x5f, 0x54, 0x59, 0x50, 0x45, 0x5f, 0x46, 0x49, 0x4c, 0x45, 0x10,
	0x01, 0x12, 0x15, 0x0a, 0x11, 0x46, 0x49, 0x4c, 0x45, 0x5f, 0x54, 0x59, 0x50, 0x45, 0x5f, 0x53,
	0x59, 0x4d, 0x4c, 0x49, 0x4e, 0x4b, 0x10, 0x02, 0x32, 0xa7, 0x01, 0x0a, 0x06, 0x41, 0x66, 0x73,
	0x6c, 0x65, 0x74, 0x12, 0x42, 0x0a, 0x07, 0x45, 0x78, 0x65, 0x63, 0x75, 0x74, 0x65, 0x12, 0x18,
	0x2e, 0x61, 0x66, 0x73, 0x6c, 0x65, 0x74, 0x70, 0x62, 0x2e, 0x45, 0x78, 0x65, 0x63, 0x75, 0x74,
	0x65, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x19, 0x2e, 0x61, 0x66, 0x73, 0x6c, 0x65,
	0x74, 0x70, 0x62, 0x2e, 0x45, 0x78, 0x65, 0x63, 0x75, 0x74, 0x65, 0x52, 0x65, 0x73, 0x70, 0x6f,
	0x6e, 0x73, 0x65, 0x28, 0x01, 0x30, 0x01, 0x12, 0x59, 0x0a, 0x10, 0x47, 0x65, 0x74, 0x52, 0x75,
	0x6e, 0x74, 0x69, 0x6d, 0x65, 0x53, 0x74, 0x61, 0x74, 0x75, 0x73, 0x12, 0x21, 0x2e, 0x61, 0x66,
	0x73, 0x6c, 0x65, 0x74, 0x70, 0x62, 0x2e, 0x47, 0x65, 0x74, 0x52, 0x75, 0x6e, 0x74, 0x69, 0x6d,
	0x65, 0x53, 0x74, 0x61, 0x74, 0x75, 0x73, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x22,
	0x2e, 0x61, 0x66, 0x73, 0x6c, 0x65, 0x74, 0x70, 0x62, 0x2e, 0x47, 0x65, 0x74, 0x52, 0x75, 0x6e,
	0x74, 0x69, 0x6d, 0x65, 0x53, 0x74, 0x61, 0x74, 0x75, 0x73, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e,
	0x73, 0x65, 0x42, 0x2e, 0x5a, 0x2c, 0x67, 0x69, 0x74, 0x68, 0x75, 0x62, 0x2e, 0x63, 0x6f, 0x6d,
	0x2f, 0x72, 0x65, 0x79, 0x6f, 0x75, 0x6e, 0x67, 0x2f, 0x61, 0x66, 0x73, 0x2f, 0x70, 0x6b, 0x67,
	0x2f, 0x61, 0x66, 0x73, 0x6c, 0x65, 0x74, 0x70, 0x62, 0x3b, 0x61, 0x66, 0x73, 0x6c, 0x65, 0x74,
	0x70, 0x62, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_api_afslet_v1_afslet_proto_rawDescOnce sync.Once
	file_api_afslet_v1_afslet_proto_rawDescData = file_api_afslet_v1_afslet_proto_rawDesc
)

func file_api_afslet_v1_afslet_proto_rawDescGZIP() []byte {
	file_api_afslet_v1_afslet_proto_rawDescOnce.Do(func() {
		file_api_afslet_v1_afslet_proto_rawDescData = protoimpl.X.CompressGZIP(file_api_afslet_v1_afslet_proto_rawDescData)
	})
	return file_api_afslet_v1_afslet_proto_rawDescData
}

var file_api_afslet_v1_afslet_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_api_afslet_v1_afslet_proto_msgTypes = make([]protoimpl.MessageInfo, 13)
var file_api_afslet_v1_afslet_proto_goTypes = []any{
	(FileType)(0),                    // 0: afsletpb.FileType
	(*ExecuteRequest)(nil),           // 1: afsletpb.ExecuteRequest
	(*StartRequest)(nil),             // 2: afsletpb.StartRequest
	(*FileEntryBegin)(nil),           // 3: afsletpb.FileEntryBegin
	(*FileChunk)(nil),                // 4: afsletpb.FileChunk
	(*FileEntryEnd)(nil),             // 5: afsletpb.FileEntryEnd
	(*ExecuteResponse)(nil),          // 6: afsletpb.ExecuteResponse
	(*LogMessage)(nil),               // 7: afsletpb.LogMessage
	(*Result)(nil),                   // 8: afsletpb.Result
	(*TarHeader)(nil),                // 9: afsletpb.TarHeader
	(*TarChunk)(nil),                 // 10: afsletpb.TarChunk
	(*Done)(nil),                     // 11: afsletpb.Done
	(*GetRuntimeStatusRequest)(nil),  // 12: afsletpb.GetRuntimeStatusRequest
	(*GetRuntimeStatusResponse)(nil), // 13: afsletpb.GetRuntimeStatusResponse
}
var file_api_afslet_v1_afslet_proto_depIdxs = []int32{
	2,  // 0: afsletpb.ExecuteRequest.start:type_name -> afsletpb.StartRequest
	3,  // 1: afsletpb.ExecuteRequest.file_begin:type_name -> afsletpb.FileEntryBegin
	4,  // 2: afsletpb.ExecuteRequest.file_chunk:type_name -> afsletpb.FileChunk
	5,  // 3: afsletpb.ExecuteRequest.file_end:type_name -> afsletpb.FileEntryEnd
	0,  // 4: afsletpb.FileEntryBegin.type:type_name -> afsletpb.FileType
	7,  // 5: afsletpb.ExecuteResponse.log:type_name -> afsletpb.LogMessage
	8,  // 6: afsletpb.ExecuteResponse.result:type_name -> afsletpb.Result
	9,  // 7: afsletpb.ExecuteResponse.tar_header:type_name -> afsletpb.TarHeader
	10, // 8: afsletpb.ExecuteResponse.tar_chunk:type_name -> afsletpb.TarChunk
	11, // 9: afsletpb.ExecuteResponse.done:type_name -> afsletpb.Done
	1,  // 10: afsletpb.Afslet.Execute:input_type -> afsletpb.ExecuteRequest
	12, // 11: afsletpb.Afslet.GetRuntimeStatus:input_type -> afsletpb.GetRuntimeStatusRequest
	6,  // 12: afsletpb.Afslet.Execute:output_type -> afsletpb.ExecuteResponse
	13, // 13: afsletpb.Afslet.GetRuntimeStatus:output_type -> afsletpb.GetRuntimeStatusResponse
	12, // [12:14] is the sub-list for method output_type
	10, // [10:12] is the sub-list for method input_type
	10, // [10:10] is the sub-list for extension type_name
	10, // [10:10] is the sub-list for extension extendee
	0,  // [0:10] is the sub-list for field type_name
}

func init() { file_api_afslet_v1_afslet_proto_init() }
func file_api_afslet_v1_afslet_proto_init() {
	if File_api_afslet_v1_afslet_proto != nil {
		return
	}
	file_api_afslet_v1_afslet_proto_msgTypes[0].OneofWrappers = []any{
		(*ExecuteRequest_Start)(nil),
		(*ExecuteRequest_FileBegin)(nil),
		(*ExecuteRequest_FileChunk)(nil),
		(*ExecuteRequest_FileEnd)(nil),
	}
	file_api_afslet_v1_afslet_proto_msgTypes[5].OneofWrappers = []any{
		(*ExecuteResponse_Log)(nil),
		(*ExecuteResponse_Result)(nil),
		(*ExecuteResponse_TarHeader)(nil),
		(*ExecuteResponse_TarChunk)(nil),
		(*ExecuteResponse_Done)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_api_afslet_v1_afslet_proto_rawDesc,
			NumEnums:      1,
			NumMessages:   13,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_api_afslet_v1_afslet_proto_goTypes,
		DependencyIndexes: file_api_afslet_v1_afslet_proto_depIdxs,
		EnumInfos:         file_api_afslet_v1_afslet_proto_enumTypes,
		MessageInfos:      file_api_afslet_v1_afslet_proto_msgTypes,
	}.Build()
	File_api_afslet_v1_afslet_proto = out.File
	file_api_afslet_v1_afslet_proto_rawDesc = nil
	file_api_afslet_v1_afslet_proto_goTypes = nil
	file_api_afslet_v1_afslet_proto_depIdxs = nil
}
