// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v4.24.2
// source: api/afslet/v1/afslet.proto

package afsletpb

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	Afslet_Execute_FullMethodName          = "/afsletpb.Afslet/Execute"
	Afslet_GetRuntimeStatus_FullMethodName = "/afsletpb.Afslet/GetRuntimeStatus"
)

// AfsletClient is the client API for Afslet service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type AfsletClient interface {
	Execute(ctx context.Context, opts ...grpc.CallOption) (grpc.BidiStreamingClient[ExecuteRequest, ExecuteResponse], error)
	GetRuntimeStatus(ctx context.Context, in *GetRuntimeStatusRequest, opts ...grpc.CallOption) (*GetRuntimeStatusResponse, error)
}

type afsletClient struct {
	cc grpc.ClientConnInterface
}

func NewAfsletClient(cc grpc.ClientConnInterface) AfsletClient {
	return &afsletClient{cc}
}

func (c *afsletClient) Execute(ctx context.Context, opts ...grpc.CallOption) (grpc.BidiStreamingClient[ExecuteRequest, ExecuteResponse], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &Afslet_ServiceDesc.Streams[0], Afslet_Execute_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[ExecuteRequest, ExecuteResponse]{ClientStream: stream}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type Afslet_ExecuteClient = grpc.BidiStreamingClient[ExecuteRequest, ExecuteResponse]

func (c *afsletClient) GetRuntimeStatus(ctx context.Context, in *GetRuntimeStatusRequest, opts ...grpc.CallOption) (*GetRuntimeStatusResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetRuntimeStatusResponse)
	err := c.cc.Invoke(ctx, Afslet_GetRuntimeStatus_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// AfsletServer is the server API for Afslet service.
// All implementations must embed UnimplementedAfsletServer
// for forward compatibility.
type AfsletServer interface {
	Execute(grpc.BidiStreamingServer[ExecuteRequest, ExecuteResponse]) error
	GetRuntimeStatus(context.Context, *GetRuntimeStatusRequest) (*GetRuntimeStatusResponse, error)
	mustEmbedUnimplementedAfsletServer()
}

// UnimplementedAfsletServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedAfsletServer struct{}

func (UnimplementedAfsletServer) Execute(grpc.BidiStreamingServer[ExecuteRequest, ExecuteResponse]) error {
	return status.Errorf(codes.Unimplemented, "method Execute not implemented")
}
func (UnimplementedAfsletServer) GetRuntimeStatus(context.Context, *GetRuntimeStatusRequest) (*GetRuntimeStatusResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetRuntimeStatus not implemented")
}
func (UnimplementedAfsletServer) mustEmbedUnimplementedAfsletServer() {}
func (UnimplementedAfsletServer) testEmbeddedByValue()                {}

// UnsafeAfsletServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to AfsletServer will
// result in compilation errors.
type UnsafeAfsletServer interface {
	mustEmbedUnimplementedAfsletServer()
}

func RegisterAfsletServer(s grpc.ServiceRegistrar, srv AfsletServer) {
	// If the following call pancis, it indicates UnimplementedAfsletServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&Afslet_ServiceDesc, srv)
}

func _Afslet_Execute_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(AfsletServer).Execute(&grpc.GenericServerStream[ExecuteRequest, ExecuteResponse]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type Afslet_ExecuteServer = grpc.BidiStreamingServer[ExecuteRequest, ExecuteResponse]

func _Afslet_GetRuntimeStatus_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetRuntimeStatusRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AfsletServer).GetRuntimeStatus(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Afslet_GetRuntimeStatus_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AfsletServer).GetRuntimeStatus(ctx, req.(*GetRuntimeStatusRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// Afslet_ServiceDesc is the grpc.ServiceDesc for Afslet service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var Afslet_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "afsletpb.Afslet",
	HandlerType: (*AfsletServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetRuntimeStatus",
			Handler:    _Afslet_GetRuntimeStatus_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "Execute",
			Handler:       _Afslet_Execute_Handler,
			ServerStreams: true,
			ClientStreams: true,
		},
	},
	Metadata: "api/afslet/v1/afslet.proto",
}
